package com.buptyouth.mybatis.dao;

import com.buptyouth.mybatis.model.Auditor;
import com.buptyouth.mybatis.model.AuditorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuditorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    int countByExample(AuditorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    int deleteByExample(AuditorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String auditorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    int insert(Auditor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    int insertSelective(Auditor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    List<Auditor> selectByExample(AuditorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    Auditor selectByPrimaryKey(String auditorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Auditor record, @Param("example") AuditorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Auditor record, @Param("example") AuditorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Auditor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Auditor record);
}