package com.buptyouth.mybatis.dao;

import com.buptyouth.mybatis.model.DWinfo;
import com.buptyouth.mybatis.model.DWinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DWinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    int countByExample(DWinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    int deleteByExample(DWinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    int insert(DWinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    int insertSelective(DWinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    List<DWinfo> selectByExample(DWinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DWinfo record, @Param("example") DWinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DWinfo record, @Param("example") DWinfoExample example);
}