package com.buptyouth.mybatis.dao;

import com.buptyouth.mybatis.model.Master;
import com.buptyouth.mybatis.model.MasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_YJS
     *
     * @mbggenerated
     */
    int countByExample(MasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_YJS
     *
     * @mbggenerated
     */
    int deleteByExample(MasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_YJS
     *
     * @mbggenerated
     */
    int insert(Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_YJS
     *
     * @mbggenerated
     */
    int insertSelective(Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_YJS
     *
     * @mbggenerated
     */
    List<Master> selectByExample(MasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_YJS
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Master record, @Param("example") MasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_YJS
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Master record, @Param("example") MasterExample example);
}