package com.buptyouth.mybatis.dao;

import com.buptyouth.mybatis.model.Schoolcalendar;
import com.buptyouth.mybatis.model.SchoolcalendarExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolcalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    int countByExample(SchoolcalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    int deleteByExample(SchoolcalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    int insert(Schoolcalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    int insertSelective(Schoolcalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    List<Schoolcalendar> selectByExample(SchoolcalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    Schoolcalendar selectByPrimaryKey(Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Schoolcalendar record, @Param("example") SchoolcalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Schoolcalendar record, @Param("example") SchoolcalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Schoolcalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schoolcalendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Schoolcalendar record);
}