package com.buptyouth.mybatis.dao;

import com.buptyouth.mybatis.model.Undergraduate;
import com.buptyouth.mybatis.model.UndergraduateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UndergraduateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BZKS
     *
     * @mbggenerated
     */
    int countByExample(UndergraduateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BZKS
     *
     * @mbggenerated
     */
    int deleteByExample(UndergraduateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BZKS
     *
     * @mbggenerated
     */
    int insert(Undergraduate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BZKS
     *
     * @mbggenerated
     */
    int insertSelective(Undergraduate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BZKS
     *
     * @mbggenerated
     */
    List<Undergraduate> selectByExampleWithBLOBs(UndergraduateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BZKS
     *
     * @mbggenerated
     */
    List<Undergraduate> selectByExample(UndergraduateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BZKS
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Undergraduate record, @Param("example") UndergraduateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BZKS
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Undergraduate record, @Param("example") UndergraduateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BZKS
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Undergraduate record, @Param("example") UndergraduateExample example);
}