package com.buptyouth.mybatis.dao;

import com.buptyouth.mybatis.model.Userwechat;
import com.buptyouth.mybatis.model.UserwechatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserwechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    int countByExample(UserwechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    int deleteByExample(UserwechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    int insert(Userwechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    int insertSelective(Userwechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    List<Userwechat> selectByExample(UserwechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    Userwechat selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Userwechat record, @Param("example") UserwechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Userwechat record, @Param("example") UserwechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userwechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwechat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userwechat record);
}