package com.buptyouth.mybatis.dao;

import com.buptyouth.mybatis.model.UserRole;
import com.buptyouth.mybatis.model.UserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    int countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("role") Integer role);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    UserRole selectByPrimaryKey(@Param("userId") String userId, @Param("role") Integer role);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userRole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRole record);
}