package com.buptyouth.mybatis.model;

import java.util.Date;

public class Apply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.apply_id
     *
     * @mbggenerated
     */
    private Integer applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.applicant_type
     *
     * @mbggenerated
     */
    private Integer applicantType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.people_number
     *
     * @mbggenerated
     */
    private Integer peopleNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.target_type
     *
     * @mbggenerated
     */
    private Integer targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.target_id
     *
     * @mbggenerated
     */
    private Integer targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.target_number
     *
     * @mbggenerated
     */
    private Integer targetNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.use_media
     *
     * @mbggenerated
     */
    private Integer useMedia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.college
     *
     * @mbggenerated
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.target_auditor
     *
     * @mbggenerated
     */
    private String targetAuditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.apply_id
     *
     * @return the value of apply.apply_id
     *
     * @mbggenerated
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.apply_id
     *
     * @param applyId the value for apply.apply_id
     *
     * @mbggenerated
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.user_id
     *
     * @return the value of apply.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.user_id
     *
     * @param userId the value for apply.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.user_type
     *
     * @return the value of apply.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.user_type
     *
     * @param userType the value for apply.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.applicant_type
     *
     * @return the value of apply.applicant_type
     *
     * @mbggenerated
     */
    public Integer getApplicantType() {
        return applicantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.applicant_type
     *
     * @param applicantType the value for apply.applicant_type
     *
     * @mbggenerated
     */
    public void setApplicantType(Integer applicantType) {
        this.applicantType = applicantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.activity_name
     *
     * @return the value of apply.activity_name
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.activity_name
     *
     * @param activityName the value for apply.activity_name
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.people_number
     *
     * @return the value of apply.people_number
     *
     * @mbggenerated
     */
    public Integer getPeopleNumber() {
        return peopleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.people_number
     *
     * @param peopleNumber the value for apply.people_number
     *
     * @mbggenerated
     */
    public void setPeopleNumber(Integer peopleNumber) {
        this.peopleNumber = peopleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.target_type
     *
     * @return the value of apply.target_type
     *
     * @mbggenerated
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.target_type
     *
     * @param targetType the value for apply.target_type
     *
     * @mbggenerated
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.target_id
     *
     * @return the value of apply.target_id
     *
     * @mbggenerated
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.target_id
     *
     * @param targetId the value for apply.target_id
     *
     * @mbggenerated
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.target_number
     *
     * @return the value of apply.target_number
     *
     * @mbggenerated
     */
    public Integer getTargetNumber() {
        return targetNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.target_number
     *
     * @param targetNumber the value for apply.target_number
     *
     * @mbggenerated
     */
    public void setTargetNumber(Integer targetNumber) {
        this.targetNumber = targetNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.use_media
     *
     * @return the value of apply.use_media
     *
     * @mbggenerated
     */
    public Integer getUseMedia() {
        return useMedia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.use_media
     *
     * @param useMedia the value for apply.use_media
     *
     * @mbggenerated
     */
    public void setUseMedia(Integer useMedia) {
        this.useMedia = useMedia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.start_time
     *
     * @return the value of apply.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.start_time
     *
     * @param startTime the value for apply.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.end_time
     *
     * @return the value of apply.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.end_time
     *
     * @param endTime the value for apply.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.create_time
     *
     * @return the value of apply.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.create_time
     *
     * @param createTime the value for apply.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.college
     *
     * @return the value of apply.college
     *
     * @mbggenerated
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.college
     *
     * @param college the value for apply.college
     *
     * @mbggenerated
     */
    public void setCollege(String college) {
        this.college = college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.department
     *
     * @return the value of apply.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.department
     *
     * @param department the value for apply.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.target_auditor
     *
     * @return the value of apply.target_auditor
     *
     * @mbggenerated
     */
    public String getTargetAuditor() {
        return targetAuditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.target_auditor
     *
     * @param targetAuditor the value for apply.target_auditor
     *
     * @mbggenerated
     */
    public void setTargetAuditor(String targetAuditor) {
        this.targetAuditor = targetAuditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.reason
     *
     * @return the value of apply.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.reason
     *
     * @param reason the value for apply.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.state
     *
     * @return the value of apply.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.state
     *
     * @param state the value for apply.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}