package com.buptyouth.mybatis.model;

public class Auditor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditor.auditor_id
     *
     * @mbggenerated
     */
    private String auditorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditor.auditor_name
     *
     * @mbggenerated
     */
    private String auditorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditor.auditor_type
     *
     * @mbggenerated
     */
    private Integer auditorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditor.college
     *
     * @mbggenerated
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditor.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditor.auditor_id
     *
     * @return the value of auditor.auditor_id
     *
     * @mbggenerated
     */
    public String getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditor.auditor_id
     *
     * @param auditorId the value for auditor.auditor_id
     *
     * @mbggenerated
     */
    public void setAuditorId(String auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditor.auditor_name
     *
     * @return the value of auditor.auditor_name
     *
     * @mbggenerated
     */
    public String getAuditorName() {
        return auditorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditor.auditor_name
     *
     * @param auditorName the value for auditor.auditor_name
     *
     * @mbggenerated
     */
    public void setAuditorName(String auditorName) {
        this.auditorName = auditorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditor.auditor_type
     *
     * @return the value of auditor.auditor_type
     *
     * @mbggenerated
     */
    public Integer getAuditorType() {
        return auditorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditor.auditor_type
     *
     * @param auditorType the value for auditor.auditor_type
     *
     * @mbggenerated
     */
    public void setAuditorType(Integer auditorType) {
        this.auditorType = auditorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditor.college
     *
     * @return the value of auditor.college
     *
     * @mbggenerated
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditor.college
     *
     * @param college the value for auditor.college
     *
     * @mbggenerated
     */
    public void setCollege(String college) {
        this.college = college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditor.department
     *
     * @return the value of auditor.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditor.department
     *
     * @param department the value for auditor.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department;
    }
}