package com.buptyouth.mybatis.model;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_id
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_name
     *
     * @mbggenerated
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.rest_number
     *
     * @mbggenerated
     */
    private Integer restNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.total_number
     *
     * @mbggenerated
     */
    private Integer totalNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_id
     *
     * @return the value of device.device_id
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_id
     *
     * @param deviceId the value for device.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_name
     *
     * @return the value of device.device_name
     *
     * @mbggenerated
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_name
     *
     * @param deviceName the value for device.device_name
     *
     * @mbggenerated
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.rest_number
     *
     * @return the value of device.rest_number
     *
     * @mbggenerated
     */
    public Integer getRestNumber() {
        return restNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.rest_number
     *
     * @param restNumber the value for device.rest_number
     *
     * @mbggenerated
     */
    public void setRestNumber(Integer restNumber) {
        this.restNumber = restNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.total_number
     *
     * @return the value of device.total_number
     *
     * @mbggenerated
     */
    public Integer getTotalNumber() {
        return totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.total_number
     *
     * @param totalNumber the value for device.total_number
     *
     * @mbggenerated
     */
    public void setTotalNumber(Integer totalNumber) {
        this.totalNumber = totalNumber;
    }
}