package com.buptyouth.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class DWinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.WID
     *
     * @mbggenerated
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.DM
     *
     * @mbggenerated
     */
    private String dm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.MC
     *
     * @mbggenerated
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.JC
     *
     * @mbggenerated
     */
    private String jc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.LBM
     *
     * @mbggenerated
     */
    private String leibieCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.YWM
     *
     * @mbggenerated
     */
    private String ywm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.LS
     *
     * @mbggenerated
     */
    private String ls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.CC
     *
     * @mbggenerated
     */
    private String cc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.BBM
     *
     * @mbggenerated
     */
    private String banbieCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.CLNF
     *
     * @mbggenerated
     */
    private String clnf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.YBZDM
     *
     * @mbggenerated
     */
    private String ybzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.QSSYRQ
     *
     * @mbggenerated
     */
    private Date qssyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.ZZSYRQ
     *
     * @mbggenerated
     */
    private Date zzsyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.PX
     *
     * @mbggenerated
     */
    private BigDecimal px;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.SFSY
     *
     * @mbggenerated
     */
    private String sfsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DW.FBQK
     *
     * @mbggenerated
     */
    private String fbqk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.WID
     *
     * @return the value of T_DW.WID
     *
     * @mbggenerated
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.WID
     *
     * @param wid the value for T_DW.WID
     *
     * @mbggenerated
     */
    public void setWid(String wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.DM
     *
     * @return the value of T_DW.DM
     *
     * @mbggenerated
     */
    public String getDm() {
        return dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.DM
     *
     * @param dm the value for T_DW.DM
     *
     * @mbggenerated
     */
    public void setDm(String dm) {
        this.dm = dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.MC
     *
     * @return the value of T_DW.MC
     *
     * @mbggenerated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.MC
     *
     * @param mc the value for T_DW.MC
     *
     * @mbggenerated
     */
    public void setMc(String mc) {
        this.mc = mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.JC
     *
     * @return the value of T_DW.JC
     *
     * @mbggenerated
     */
    public String getJc() {
        return jc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.JC
     *
     * @param jc the value for T_DW.JC
     *
     * @mbggenerated
     */
    public void setJc(String jc) {
        this.jc = jc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.LBM
     *
     * @return the value of T_DW.LBM
     *
     * @mbggenerated
     */
    public String getLeibieCode() {
        return leibieCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.LBM
     *
     * @param leibieCode the value for T_DW.LBM
     *
     * @mbggenerated
     */
    public void setLeibieCode(String leibieCode) {
        this.leibieCode = leibieCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.YWM
     *
     * @return the value of T_DW.YWM
     *
     * @mbggenerated
     */
    public String getYwm() {
        return ywm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.YWM
     *
     * @param ywm the value for T_DW.YWM
     *
     * @mbggenerated
     */
    public void setYwm(String ywm) {
        this.ywm = ywm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.LS
     *
     * @return the value of T_DW.LS
     *
     * @mbggenerated
     */
    public String getLs() {
        return ls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.LS
     *
     * @param ls the value for T_DW.LS
     *
     * @mbggenerated
     */
    public void setLs(String ls) {
        this.ls = ls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.CC
     *
     * @return the value of T_DW.CC
     *
     * @mbggenerated
     */
    public String getCc() {
        return cc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.CC
     *
     * @param cc the value for T_DW.CC
     *
     * @mbggenerated
     */
    public void setCc(String cc) {
        this.cc = cc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.BBM
     *
     * @return the value of T_DW.BBM
     *
     * @mbggenerated
     */
    public String getBanbieCode() {
        return banbieCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.BBM
     *
     * @param banbieCode the value for T_DW.BBM
     *
     * @mbggenerated
     */
    public void setBanbieCode(String banbieCode) {
        this.banbieCode = banbieCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.CLNF
     *
     * @return the value of T_DW.CLNF
     *
     * @mbggenerated
     */
    public String getClnf() {
        return clnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.CLNF
     *
     * @param clnf the value for T_DW.CLNF
     *
     * @mbggenerated
     */
    public void setClnf(String clnf) {
        this.clnf = clnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.YBZDM
     *
     * @return the value of T_DW.YBZDM
     *
     * @mbggenerated
     */
    public String getYbzdm() {
        return ybzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.YBZDM
     *
     * @param ybzdm the value for T_DW.YBZDM
     *
     * @mbggenerated
     */
    public void setYbzdm(String ybzdm) {
        this.ybzdm = ybzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.QSSYRQ
     *
     * @return the value of T_DW.QSSYRQ
     *
     * @mbggenerated
     */
    public Date getQssyrq() {
        return qssyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.QSSYRQ
     *
     * @param qssyrq the value for T_DW.QSSYRQ
     *
     * @mbggenerated
     */
    public void setQssyrq(Date qssyrq) {
        this.qssyrq = qssyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.ZZSYRQ
     *
     * @return the value of T_DW.ZZSYRQ
     *
     * @mbggenerated
     */
    public Date getZzsyrq() {
        return zzsyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.ZZSYRQ
     *
     * @param zzsyrq the value for T_DW.ZZSYRQ
     *
     * @mbggenerated
     */
    public void setZzsyrq(Date zzsyrq) {
        this.zzsyrq = zzsyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.PX
     *
     * @return the value of T_DW.PX
     *
     * @mbggenerated
     */
    public BigDecimal getPx() {
        return px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.PX
     *
     * @param px the value for T_DW.PX
     *
     * @mbggenerated
     */
    public void setPx(BigDecimal px) {
        this.px = px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.SFSY
     *
     * @return the value of T_DW.SFSY
     *
     * @mbggenerated
     */
    public String getSfsy() {
        return sfsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.SFSY
     *
     * @param sfsy the value for T_DW.SFSY
     *
     * @mbggenerated
     */
    public void setSfsy(String sfsy) {
        this.sfsy = sfsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DW.FBQK
     *
     * @return the value of T_DW.FBQK
     *
     * @mbggenerated
     */
    public String getFbqk() {
        return fbqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DW.FBQK
     *
     * @param fbqk the value for T_DW.FBQK
     *
     * @mbggenerated
     */
    public void setFbqk(String fbqk) {
        this.fbqk = fbqk;
    }
}