package com.buptyouth.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DWinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public DWinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andWidIsNull() {
            addCriterion("WID is null");
            return (Criteria) this;
        }

        public Criteria andWidIsNotNull() {
            addCriterion("WID is not null");
            return (Criteria) this;
        }

        public Criteria andWidEqualTo(String value) {
            addCriterion("WID =", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotEqualTo(String value) {
            addCriterion("WID <>", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidGreaterThan(String value) {
            addCriterion("WID >", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidGreaterThanOrEqualTo(String value) {
            addCriterion("WID >=", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidLessThan(String value) {
            addCriterion("WID <", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidLessThanOrEqualTo(String value) {
            addCriterion("WID <=", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidLike(String value) {
            addCriterion("WID like", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotLike(String value) {
            addCriterion("WID not like", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidIn(List<String> values) {
            addCriterion("WID in", values, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotIn(List<String> values) {
            addCriterion("WID not in", values, "wid");
            return (Criteria) this;
        }

        public Criteria andWidBetween(String value1, String value2) {
            addCriterion("WID between", value1, value2, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotBetween(String value1, String value2) {
            addCriterion("WID not between", value1, value2, "wid");
            return (Criteria) this;
        }

        public Criteria andDmIsNull() {
            addCriterion("DM is null");
            return (Criteria) this;
        }

        public Criteria andDmIsNotNull() {
            addCriterion("DM is not null");
            return (Criteria) this;
        }

        public Criteria andDmEqualTo(String value) {
            addCriterion("DM =", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmNotEqualTo(String value) {
            addCriterion("DM <>", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmGreaterThan(String value) {
            addCriterion("DM >", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmGreaterThanOrEqualTo(String value) {
            addCriterion("DM >=", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmLessThan(String value) {
            addCriterion("DM <", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmLessThanOrEqualTo(String value) {
            addCriterion("DM <=", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmLike(String value) {
            addCriterion("DM like", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmNotLike(String value) {
            addCriterion("DM not like", value, "dm");
            return (Criteria) this;
        }

        public Criteria andDmIn(List<String> values) {
            addCriterion("DM in", values, "dm");
            return (Criteria) this;
        }

        public Criteria andDmNotIn(List<String> values) {
            addCriterion("DM not in", values, "dm");
            return (Criteria) this;
        }

        public Criteria andDmBetween(String value1, String value2) {
            addCriterion("DM between", value1, value2, "dm");
            return (Criteria) this;
        }

        public Criteria andDmNotBetween(String value1, String value2) {
            addCriterion("DM not between", value1, value2, "dm");
            return (Criteria) this;
        }

        public Criteria andMcIsNull() {
            addCriterion("MC is null");
            return (Criteria) this;
        }

        public Criteria andMcIsNotNull() {
            addCriterion("MC is not null");
            return (Criteria) this;
        }

        public Criteria andMcEqualTo(String value) {
            addCriterion("MC =", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotEqualTo(String value) {
            addCriterion("MC <>", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcGreaterThan(String value) {
            addCriterion("MC >", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcGreaterThanOrEqualTo(String value) {
            addCriterion("MC >=", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcLessThan(String value) {
            addCriterion("MC <", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcLessThanOrEqualTo(String value) {
            addCriterion("MC <=", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcLike(String value) {
            addCriterion("MC like", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotLike(String value) {
            addCriterion("MC not like", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcIn(List<String> values) {
            addCriterion("MC in", values, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotIn(List<String> values) {
            addCriterion("MC not in", values, "mc");
            return (Criteria) this;
        }

        public Criteria andMcBetween(String value1, String value2) {
            addCriterion("MC between", value1, value2, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotBetween(String value1, String value2) {
            addCriterion("MC not between", value1, value2, "mc");
            return (Criteria) this;
        }

        public Criteria andJcIsNull() {
            addCriterion("JC is null");
            return (Criteria) this;
        }

        public Criteria andJcIsNotNull() {
            addCriterion("JC is not null");
            return (Criteria) this;
        }

        public Criteria andJcEqualTo(String value) {
            addCriterion("JC =", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcNotEqualTo(String value) {
            addCriterion("JC <>", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcGreaterThan(String value) {
            addCriterion("JC >", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcGreaterThanOrEqualTo(String value) {
            addCriterion("JC >=", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcLessThan(String value) {
            addCriterion("JC <", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcLessThanOrEqualTo(String value) {
            addCriterion("JC <=", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcLike(String value) {
            addCriterion("JC like", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcNotLike(String value) {
            addCriterion("JC not like", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcIn(List<String> values) {
            addCriterion("JC in", values, "jc");
            return (Criteria) this;
        }

        public Criteria andJcNotIn(List<String> values) {
            addCriterion("JC not in", values, "jc");
            return (Criteria) this;
        }

        public Criteria andJcBetween(String value1, String value2) {
            addCriterion("JC between", value1, value2, "jc");
            return (Criteria) this;
        }

        public Criteria andJcNotBetween(String value1, String value2) {
            addCriterion("JC not between", value1, value2, "jc");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeIsNull() {
            addCriterion("LBM is null");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeIsNotNull() {
            addCriterion("LBM is not null");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeEqualTo(String value) {
            addCriterion("LBM =", value, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeNotEqualTo(String value) {
            addCriterion("LBM <>", value, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeGreaterThan(String value) {
            addCriterion("LBM >", value, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeGreaterThanOrEqualTo(String value) {
            addCriterion("LBM >=", value, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeLessThan(String value) {
            addCriterion("LBM <", value, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeLessThanOrEqualTo(String value) {
            addCriterion("LBM <=", value, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeLike(String value) {
            addCriterion("LBM like", value, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeNotLike(String value) {
            addCriterion("LBM not like", value, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeIn(List<String> values) {
            addCriterion("LBM in", values, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeNotIn(List<String> values) {
            addCriterion("LBM not in", values, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeBetween(String value1, String value2) {
            addCriterion("LBM between", value1, value2, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andLeibieCodeNotBetween(String value1, String value2) {
            addCriterion("LBM not between", value1, value2, "leibieCode");
            return (Criteria) this;
        }

        public Criteria andYwmIsNull() {
            addCriterion("YWM is null");
            return (Criteria) this;
        }

        public Criteria andYwmIsNotNull() {
            addCriterion("YWM is not null");
            return (Criteria) this;
        }

        public Criteria andYwmEqualTo(String value) {
            addCriterion("YWM =", value, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmNotEqualTo(String value) {
            addCriterion("YWM <>", value, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmGreaterThan(String value) {
            addCriterion("YWM >", value, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmGreaterThanOrEqualTo(String value) {
            addCriterion("YWM >=", value, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmLessThan(String value) {
            addCriterion("YWM <", value, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmLessThanOrEqualTo(String value) {
            addCriterion("YWM <=", value, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmLike(String value) {
            addCriterion("YWM like", value, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmNotLike(String value) {
            addCriterion("YWM not like", value, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmIn(List<String> values) {
            addCriterion("YWM in", values, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmNotIn(List<String> values) {
            addCriterion("YWM not in", values, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmBetween(String value1, String value2) {
            addCriterion("YWM between", value1, value2, "ywm");
            return (Criteria) this;
        }

        public Criteria andYwmNotBetween(String value1, String value2) {
            addCriterion("YWM not between", value1, value2, "ywm");
            return (Criteria) this;
        }

        public Criteria andLsIsNull() {
            addCriterion("LS is null");
            return (Criteria) this;
        }

        public Criteria andLsIsNotNull() {
            addCriterion("LS is not null");
            return (Criteria) this;
        }

        public Criteria andLsEqualTo(String value) {
            addCriterion("LS =", value, "ls");
            return (Criteria) this;
        }

        public Criteria andLsNotEqualTo(String value) {
            addCriterion("LS <>", value, "ls");
            return (Criteria) this;
        }

        public Criteria andLsGreaterThan(String value) {
            addCriterion("LS >", value, "ls");
            return (Criteria) this;
        }

        public Criteria andLsGreaterThanOrEqualTo(String value) {
            addCriterion("LS >=", value, "ls");
            return (Criteria) this;
        }

        public Criteria andLsLessThan(String value) {
            addCriterion("LS <", value, "ls");
            return (Criteria) this;
        }

        public Criteria andLsLessThanOrEqualTo(String value) {
            addCriterion("LS <=", value, "ls");
            return (Criteria) this;
        }

        public Criteria andLsLike(String value) {
            addCriterion("LS like", value, "ls");
            return (Criteria) this;
        }

        public Criteria andLsNotLike(String value) {
            addCriterion("LS not like", value, "ls");
            return (Criteria) this;
        }

        public Criteria andLsIn(List<String> values) {
            addCriterion("LS in", values, "ls");
            return (Criteria) this;
        }

        public Criteria andLsNotIn(List<String> values) {
            addCriterion("LS not in", values, "ls");
            return (Criteria) this;
        }

        public Criteria andLsBetween(String value1, String value2) {
            addCriterion("LS between", value1, value2, "ls");
            return (Criteria) this;
        }

        public Criteria andLsNotBetween(String value1, String value2) {
            addCriterion("LS not between", value1, value2, "ls");
            return (Criteria) this;
        }

        public Criteria andCcIsNull() {
            addCriterion("CC is null");
            return (Criteria) this;
        }

        public Criteria andCcIsNotNull() {
            addCriterion("CC is not null");
            return (Criteria) this;
        }

        public Criteria andCcEqualTo(String value) {
            addCriterion("CC =", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcNotEqualTo(String value) {
            addCriterion("CC <>", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcGreaterThan(String value) {
            addCriterion("CC >", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcGreaterThanOrEqualTo(String value) {
            addCriterion("CC >=", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcLessThan(String value) {
            addCriterion("CC <", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcLessThanOrEqualTo(String value) {
            addCriterion("CC <=", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcLike(String value) {
            addCriterion("CC like", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcNotLike(String value) {
            addCriterion("CC not like", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcIn(List<String> values) {
            addCriterion("CC in", values, "cc");
            return (Criteria) this;
        }

        public Criteria andCcNotIn(List<String> values) {
            addCriterion("CC not in", values, "cc");
            return (Criteria) this;
        }

        public Criteria andCcBetween(String value1, String value2) {
            addCriterion("CC between", value1, value2, "cc");
            return (Criteria) this;
        }

        public Criteria andCcNotBetween(String value1, String value2) {
            addCriterion("CC not between", value1, value2, "cc");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeIsNull() {
            addCriterion("BBM is null");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeIsNotNull() {
            addCriterion("BBM is not null");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeEqualTo(String value) {
            addCriterion("BBM =", value, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeNotEqualTo(String value) {
            addCriterion("BBM <>", value, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeGreaterThan(String value) {
            addCriterion("BBM >", value, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeGreaterThanOrEqualTo(String value) {
            addCriterion("BBM >=", value, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeLessThan(String value) {
            addCriterion("BBM <", value, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeLessThanOrEqualTo(String value) {
            addCriterion("BBM <=", value, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeLike(String value) {
            addCriterion("BBM like", value, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeNotLike(String value) {
            addCriterion("BBM not like", value, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeIn(List<String> values) {
            addCriterion("BBM in", values, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeNotIn(List<String> values) {
            addCriterion("BBM not in", values, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeBetween(String value1, String value2) {
            addCriterion("BBM between", value1, value2, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andBanbieCodeNotBetween(String value1, String value2) {
            addCriterion("BBM not between", value1, value2, "banbieCode");
            return (Criteria) this;
        }

        public Criteria andClnfIsNull() {
            addCriterion("CLNF is null");
            return (Criteria) this;
        }

        public Criteria andClnfIsNotNull() {
            addCriterion("CLNF is not null");
            return (Criteria) this;
        }

        public Criteria andClnfEqualTo(String value) {
            addCriterion("CLNF =", value, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfNotEqualTo(String value) {
            addCriterion("CLNF <>", value, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfGreaterThan(String value) {
            addCriterion("CLNF >", value, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfGreaterThanOrEqualTo(String value) {
            addCriterion("CLNF >=", value, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfLessThan(String value) {
            addCriterion("CLNF <", value, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfLessThanOrEqualTo(String value) {
            addCriterion("CLNF <=", value, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfLike(String value) {
            addCriterion("CLNF like", value, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfNotLike(String value) {
            addCriterion("CLNF not like", value, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfIn(List<String> values) {
            addCriterion("CLNF in", values, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfNotIn(List<String> values) {
            addCriterion("CLNF not in", values, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfBetween(String value1, String value2) {
            addCriterion("CLNF between", value1, value2, "clnf");
            return (Criteria) this;
        }

        public Criteria andClnfNotBetween(String value1, String value2) {
            addCriterion("CLNF not between", value1, value2, "clnf");
            return (Criteria) this;
        }

        public Criteria andYbzdmIsNull() {
            addCriterion("YBZDM is null");
            return (Criteria) this;
        }

        public Criteria andYbzdmIsNotNull() {
            addCriterion("YBZDM is not null");
            return (Criteria) this;
        }

        public Criteria andYbzdmEqualTo(String value) {
            addCriterion("YBZDM =", value, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmNotEqualTo(String value) {
            addCriterion("YBZDM <>", value, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmGreaterThan(String value) {
            addCriterion("YBZDM >", value, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmGreaterThanOrEqualTo(String value) {
            addCriterion("YBZDM >=", value, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmLessThan(String value) {
            addCriterion("YBZDM <", value, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmLessThanOrEqualTo(String value) {
            addCriterion("YBZDM <=", value, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmLike(String value) {
            addCriterion("YBZDM like", value, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmNotLike(String value) {
            addCriterion("YBZDM not like", value, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmIn(List<String> values) {
            addCriterion("YBZDM in", values, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmNotIn(List<String> values) {
            addCriterion("YBZDM not in", values, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmBetween(String value1, String value2) {
            addCriterion("YBZDM between", value1, value2, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andYbzdmNotBetween(String value1, String value2) {
            addCriterion("YBZDM not between", value1, value2, "ybzdm");
            return (Criteria) this;
        }

        public Criteria andQssyrqIsNull() {
            addCriterion("QSSYRQ is null");
            return (Criteria) this;
        }

        public Criteria andQssyrqIsNotNull() {
            addCriterion("QSSYRQ is not null");
            return (Criteria) this;
        }

        public Criteria andQssyrqEqualTo(Date value) {
            addCriterionForJDBCDate("QSSYRQ =", value, "qssyrq");
            return (Criteria) this;
        }

        public Criteria andQssyrqNotEqualTo(Date value) {
            addCriterionForJDBCDate("QSSYRQ <>", value, "qssyrq");
            return (Criteria) this;
        }

        public Criteria andQssyrqGreaterThan(Date value) {
            addCriterionForJDBCDate("QSSYRQ >", value, "qssyrq");
            return (Criteria) this;
        }

        public Criteria andQssyrqGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("QSSYRQ >=", value, "qssyrq");
            return (Criteria) this;
        }

        public Criteria andQssyrqLessThan(Date value) {
            addCriterionForJDBCDate("QSSYRQ <", value, "qssyrq");
            return (Criteria) this;
        }

        public Criteria andQssyrqLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("QSSYRQ <=", value, "qssyrq");
            return (Criteria) this;
        }

        public Criteria andQssyrqIn(List<Date> values) {
            addCriterionForJDBCDate("QSSYRQ in", values, "qssyrq");
            return (Criteria) this;
        }

        public Criteria andQssyrqNotIn(List<Date> values) {
            addCriterionForJDBCDate("QSSYRQ not in", values, "qssyrq");
            return (Criteria) this;
        }

        public Criteria andQssyrqBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("QSSYRQ between", value1, value2, "qssyrq");
            return (Criteria) this;
        }

        public Criteria andQssyrqNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("QSSYRQ not between", value1, value2, "qssyrq");
            return (Criteria) this;
        }

        public Criteria andZzsyrqIsNull() {
            addCriterion("ZZSYRQ is null");
            return (Criteria) this;
        }

        public Criteria andZzsyrqIsNotNull() {
            addCriterion("ZZSYRQ is not null");
            return (Criteria) this;
        }

        public Criteria andZzsyrqEqualTo(Date value) {
            addCriterionForJDBCDate("ZZSYRQ =", value, "zzsyrq");
            return (Criteria) this;
        }

        public Criteria andZzsyrqNotEqualTo(Date value) {
            addCriterionForJDBCDate("ZZSYRQ <>", value, "zzsyrq");
            return (Criteria) this;
        }

        public Criteria andZzsyrqGreaterThan(Date value) {
            addCriterionForJDBCDate("ZZSYRQ >", value, "zzsyrq");
            return (Criteria) this;
        }

        public Criteria andZzsyrqGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ZZSYRQ >=", value, "zzsyrq");
            return (Criteria) this;
        }

        public Criteria andZzsyrqLessThan(Date value) {
            addCriterionForJDBCDate("ZZSYRQ <", value, "zzsyrq");
            return (Criteria) this;
        }

        public Criteria andZzsyrqLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ZZSYRQ <=", value, "zzsyrq");
            return (Criteria) this;
        }

        public Criteria andZzsyrqIn(List<Date> values) {
            addCriterionForJDBCDate("ZZSYRQ in", values, "zzsyrq");
            return (Criteria) this;
        }

        public Criteria andZzsyrqNotIn(List<Date> values) {
            addCriterionForJDBCDate("ZZSYRQ not in", values, "zzsyrq");
            return (Criteria) this;
        }

        public Criteria andZzsyrqBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ZZSYRQ between", value1, value2, "zzsyrq");
            return (Criteria) this;
        }

        public Criteria andZzsyrqNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ZZSYRQ not between", value1, value2, "zzsyrq");
            return (Criteria) this;
        }

        public Criteria andPxIsNull() {
            addCriterion("PX is null");
            return (Criteria) this;
        }

        public Criteria andPxIsNotNull() {
            addCriterion("PX is not null");
            return (Criteria) this;
        }

        public Criteria andPxEqualTo(BigDecimal value) {
            addCriterion("PX =", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxNotEqualTo(BigDecimal value) {
            addCriterion("PX <>", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxGreaterThan(BigDecimal value) {
            addCriterion("PX >", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PX >=", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxLessThan(BigDecimal value) {
            addCriterion("PX <", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PX <=", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxIn(List<BigDecimal> values) {
            addCriterion("PX in", values, "px");
            return (Criteria) this;
        }

        public Criteria andPxNotIn(List<BigDecimal> values) {
            addCriterion("PX not in", values, "px");
            return (Criteria) this;
        }

        public Criteria andPxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PX between", value1, value2, "px");
            return (Criteria) this;
        }

        public Criteria andPxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PX not between", value1, value2, "px");
            return (Criteria) this;
        }

        public Criteria andSfsyIsNull() {
            addCriterion("SFSY is null");
            return (Criteria) this;
        }

        public Criteria andSfsyIsNotNull() {
            addCriterion("SFSY is not null");
            return (Criteria) this;
        }

        public Criteria andSfsyEqualTo(String value) {
            addCriterion("SFSY =", value, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyNotEqualTo(String value) {
            addCriterion("SFSY <>", value, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyGreaterThan(String value) {
            addCriterion("SFSY >", value, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyGreaterThanOrEqualTo(String value) {
            addCriterion("SFSY >=", value, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyLessThan(String value) {
            addCriterion("SFSY <", value, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyLessThanOrEqualTo(String value) {
            addCriterion("SFSY <=", value, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyLike(String value) {
            addCriterion("SFSY like", value, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyNotLike(String value) {
            addCriterion("SFSY not like", value, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyIn(List<String> values) {
            addCriterion("SFSY in", values, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyNotIn(List<String> values) {
            addCriterion("SFSY not in", values, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyBetween(String value1, String value2) {
            addCriterion("SFSY between", value1, value2, "sfsy");
            return (Criteria) this;
        }

        public Criteria andSfsyNotBetween(String value1, String value2) {
            addCriterion("SFSY not between", value1, value2, "sfsy");
            return (Criteria) this;
        }

        public Criteria andFbqkIsNull() {
            addCriterion("FBQK is null");
            return (Criteria) this;
        }

        public Criteria andFbqkIsNotNull() {
            addCriterion("FBQK is not null");
            return (Criteria) this;
        }

        public Criteria andFbqkEqualTo(String value) {
            addCriterion("FBQK =", value, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkNotEqualTo(String value) {
            addCriterion("FBQK <>", value, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkGreaterThan(String value) {
            addCriterion("FBQK >", value, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkGreaterThanOrEqualTo(String value) {
            addCriterion("FBQK >=", value, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkLessThan(String value) {
            addCriterion("FBQK <", value, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkLessThanOrEqualTo(String value) {
            addCriterion("FBQK <=", value, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkLike(String value) {
            addCriterion("FBQK like", value, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkNotLike(String value) {
            addCriterion("FBQK not like", value, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkIn(List<String> values) {
            addCriterion("FBQK in", values, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkNotIn(List<String> values) {
            addCriterion("FBQK not in", values, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkBetween(String value1, String value2) {
            addCriterion("FBQK between", value1, value2, "fbqk");
            return (Criteria) this;
        }

        public Criteria andFbqkNotBetween(String value1, String value2) {
            addCriterion("FBQK not between", value1, value2, "fbqk");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_DW
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_DW
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}