package com.buptyouth.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class Master {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.WID
     *
     * @mbggenerated
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XH
     *
     * @mbggenerated
     */
    private String schoolNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XM
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XMPY
     *
     * @mbggenerated
     */
    private String xmpy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.CYM
     *
     * @mbggenerated
     */
    private String cym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.YWM
     *
     * @mbggenerated
     */
    private String ywm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.MZDM
     *
     * @mbggenerated
     */
    private String mzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XBDM
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XXDM
     *
     * @mbggenerated
     */
    private String xxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.ZZMMDM
     *
     * @mbggenerated
     */
    private String zzmmdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SFZJH
     *
     * @mbggenerated
     */
    private String sfzjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.CSRQ
     *
     * @mbggenerated
     */
    private String csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.CSDDM
     *
     * @mbggenerated
     */
    private String csddm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.JGDM
     *
     * @mbggenerated
     */
    private String jgdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.JKZKDM
     *
     * @mbggenerated
     */
    private String jkzkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.HYZKDM
     *
     * @mbggenerated
     */
    private String hyzkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.GATQDM
     *
     * @mbggenerated
     */
    private String gatqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.GJDQDM
     *
     * @mbggenerated
     */
    private String gjdqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.BYYX
     *
     * @mbggenerated
     */
    private String byyx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.BYZYDM
     *
     * @mbggenerated
     */
    private String byzydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.ZYDZ
     *
     * @mbggenerated
     */
    private String zydz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.CLRQ
     *
     * @mbggenerated
     */
    private Date clrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.CZLX
     *
     * @mbggenerated
     */
    private String czlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.CZZ
     *
     * @mbggenerated
     */
    private String czz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.BY1
     *
     * @mbggenerated
     */
    private String by1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XQ
     *
     * @mbggenerated
     */
    private String xq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.HKSZD
     *
     * @mbggenerated
     */
    private String hkszd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.YXDM
     *
     * @mbggenerated
     */
    private String collegeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SFZJLXM
     *
     * @mbggenerated
     */
    private String sfzjlxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.RXZYDM
     *
     * @mbggenerated
     */
    private String rxzydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XKMLDM
     *
     * @mbggenerated
     */
    private String xkmldm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XXFSDM
     *
     * @mbggenerated
     */
    private String xxfsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.PYFSDM
     *
     * @mbggenerated
     */
    private String pyfsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XSLBDM
     *
     * @mbggenerated
     */
    private String xslbdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.YJFX
     *
     * @mbggenerated
     */
    private String yjfx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SFZZS
     *
     * @mbggenerated
     */
    private String sfzzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.ZZGH
     *
     * @mbggenerated
     */
    private String zzgh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.DSZGH
     *
     * @mbggenerated
     */
    private String dszgh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SYDDM
     *
     * @mbggenerated
     */
    private String syddm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.HSSBKDM
     *
     * @mbggenerated
     */
    private String hssbkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XSLYDM
     *
     * @mbggenerated
     */
    private String xslydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.WTPYDW
     *
     * @mbggenerated
     */
    private String wtpydw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.PYCCDM
     *
     * @mbggenerated
     */
    private String pyccdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.RXNJ
     *
     * @mbggenerated
     */
    private String rxnj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XZNJ
     *
     * @mbggenerated
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.HDXLFSDM
     *
     * @mbggenerated
     */
    private String hdxlfsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XZZYDM
     *
     * @mbggenerated
     */
    private String xzzydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.BH
     *
     * @mbggenerated
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XZ
     *
     * @mbggenerated
     */
    private BigDecimal xz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.DYWYYZ
     *
     * @mbggenerated
     */
    private String dywyyz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.HKXZDM
     *
     * @mbggenerated
     */
    private String hkxzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.DYWYSP
     *
     * @mbggenerated
     */
    private String dywysp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.DEWYYZ
     *
     * @mbggenerated
     */
    private String dewyyz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.DEWYSP
     *
     * @mbggenerated
     */
    private String dewysp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.JDXWDM
     *
     * @mbggenerated
     */
    private String jdxwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.JDXLDM
     *
     * @mbggenerated
     */
    private String jdxldm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XJZT
     *
     * @mbggenerated
     */
    private String xjzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.ZCQK
     *
     * @mbggenerated
     */
    private String registerInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.YJBYNF
     *
     * @mbggenerated
     */
    private String yjbynf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.YJBYJD
     *
     * @mbggenerated
     */
    private String yjbyjd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.ZHCP
     *
     * @mbggenerated
     */
    private String zhcp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SG
     *
     * @mbggenerated
     */
    private BigDecimal sg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XWLXDM
     *
     * @mbggenerated
     */
    private String xwlxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.TZ
     *
     * @mbggenerated
     */
    private BigDecimal tz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SJBYSJ
     *
     * @mbggenerated
     */
    private String sjbysj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.RXNY
     *
     * @mbggenerated
     */
    private String rxny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SJLY
     *
     * @mbggenerated
     */
    private String sjly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.DQZTDM
     *
     * @mbggenerated
     */
    private String dqztdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SFZX
     *
     * @mbggenerated
     */
    private String sfzx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SJBBH
     *
     * @mbggenerated
     */
    private String sjbbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SFXFZ
     *
     * @mbggenerated
     */
    private String sfxfz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.LDFSDM
     *
     * @mbggenerated
     */
    private String ldfsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.GATQWDM
     *
     * @mbggenerated
     */
    private String gatqwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.XYZJDM
     *
     * @mbggenerated
     */
    private String xyzjdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SFZJYXKSQ
     *
     * @mbggenerated
     */
    private String sfzjyxksq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SFZJYXJZQ
     *
     * @mbggenerated
     */
    private String sfzjyxjzq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SFDSZN
     *
     * @mbggenerated
     */
    private String sfdszn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.YXH
     *
     * @mbggenerated
     */
    private String yxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.LYDQDM
     *
     * @mbggenerated
     */
    private String lydqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.JG
     *
     * @mbggenerated
     */
    private String jg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SFZJYXQ
     *
     * @mbggenerated
     */
    private String sfzjyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SFBY
     *
     * @mbggenerated
     */
    private String sfby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SS
     *
     * @mbggenerated
     */
    private String ss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.SSDH
     *
     * @mbggenerated
     */
    private String ssdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.GRDH
     *
     * @mbggenerated
     */
    private String grdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_YJS.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.WID
     *
     * @return the value of T_YJS.WID
     *
     * @mbggenerated
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.WID
     *
     * @param wid the value for T_YJS.WID
     *
     * @mbggenerated
     */
    public void setWid(String wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XH
     *
     * @return the value of T_YJS.XH
     *
     * @mbggenerated
     */
    public String getSchoolNumber() {
        return schoolNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XH
     *
     * @param schoolNumber the value for T_YJS.XH
     *
     * @mbggenerated
     */
    public void setSchoolNumber(String schoolNumber) {
        this.schoolNumber = schoolNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XM
     *
     * @return the value of T_YJS.XM
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XM
     *
     * @param userName the value for T_YJS.XM
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XMPY
     *
     * @return the value of T_YJS.XMPY
     *
     * @mbggenerated
     */
    public String getXmpy() {
        return xmpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XMPY
     *
     * @param xmpy the value for T_YJS.XMPY
     *
     * @mbggenerated
     */
    public void setXmpy(String xmpy) {
        this.xmpy = xmpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.CYM
     *
     * @return the value of T_YJS.CYM
     *
     * @mbggenerated
     */
    public String getCym() {
        return cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.CYM
     *
     * @param cym the value for T_YJS.CYM
     *
     * @mbggenerated
     */
    public void setCym(String cym) {
        this.cym = cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.YWM
     *
     * @return the value of T_YJS.YWM
     *
     * @mbggenerated
     */
    public String getYwm() {
        return ywm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.YWM
     *
     * @param ywm the value for T_YJS.YWM
     *
     * @mbggenerated
     */
    public void setYwm(String ywm) {
        this.ywm = ywm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.MZDM
     *
     * @return the value of T_YJS.MZDM
     *
     * @mbggenerated
     */
    public String getMzdm() {
        return mzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.MZDM
     *
     * @param mzdm the value for T_YJS.MZDM
     *
     * @mbggenerated
     */
    public void setMzdm(String mzdm) {
        this.mzdm = mzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XBDM
     *
     * @return the value of T_YJS.XBDM
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XBDM
     *
     * @param gender the value for T_YJS.XBDM
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XXDM
     *
     * @return the value of T_YJS.XXDM
     *
     * @mbggenerated
     */
    public String getXxdm() {
        return xxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XXDM
     *
     * @param xxdm the value for T_YJS.XXDM
     *
     * @mbggenerated
     */
    public void setXxdm(String xxdm) {
        this.xxdm = xxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.ZZMMDM
     *
     * @return the value of T_YJS.ZZMMDM
     *
     * @mbggenerated
     */
    public String getZzmmdm() {
        return zzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.ZZMMDM
     *
     * @param zzmmdm the value for T_YJS.ZZMMDM
     *
     * @mbggenerated
     */
    public void setZzmmdm(String zzmmdm) {
        this.zzmmdm = zzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SFZJH
     *
     * @return the value of T_YJS.SFZJH
     *
     * @mbggenerated
     */
    public String getSfzjh() {
        return sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SFZJH
     *
     * @param sfzjh the value for T_YJS.SFZJH
     *
     * @mbggenerated
     */
    public void setSfzjh(String sfzjh) {
        this.sfzjh = sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.CSRQ
     *
     * @return the value of T_YJS.CSRQ
     *
     * @mbggenerated
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.CSRQ
     *
     * @param csrq the value for T_YJS.CSRQ
     *
     * @mbggenerated
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.CSDDM
     *
     * @return the value of T_YJS.CSDDM
     *
     * @mbggenerated
     */
    public String getCsddm() {
        return csddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.CSDDM
     *
     * @param csddm the value for T_YJS.CSDDM
     *
     * @mbggenerated
     */
    public void setCsddm(String csddm) {
        this.csddm = csddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.JGDM
     *
     * @return the value of T_YJS.JGDM
     *
     * @mbggenerated
     */
    public String getJgdm() {
        return jgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.JGDM
     *
     * @param jgdm the value for T_YJS.JGDM
     *
     * @mbggenerated
     */
    public void setJgdm(String jgdm) {
        this.jgdm = jgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.JKZKDM
     *
     * @return the value of T_YJS.JKZKDM
     *
     * @mbggenerated
     */
    public String getJkzkdm() {
        return jkzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.JKZKDM
     *
     * @param jkzkdm the value for T_YJS.JKZKDM
     *
     * @mbggenerated
     */
    public void setJkzkdm(String jkzkdm) {
        this.jkzkdm = jkzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.HYZKDM
     *
     * @return the value of T_YJS.HYZKDM
     *
     * @mbggenerated
     */
    public String getHyzkdm() {
        return hyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.HYZKDM
     *
     * @param hyzkdm the value for T_YJS.HYZKDM
     *
     * @mbggenerated
     */
    public void setHyzkdm(String hyzkdm) {
        this.hyzkdm = hyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.GATQDM
     *
     * @return the value of T_YJS.GATQDM
     *
     * @mbggenerated
     */
    public String getGatqdm() {
        return gatqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.GATQDM
     *
     * @param gatqdm the value for T_YJS.GATQDM
     *
     * @mbggenerated
     */
    public void setGatqdm(String gatqdm) {
        this.gatqdm = gatqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.GJDQDM
     *
     * @return the value of T_YJS.GJDQDM
     *
     * @mbggenerated
     */
    public String getGjdqdm() {
        return gjdqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.GJDQDM
     *
     * @param gjdqdm the value for T_YJS.GJDQDM
     *
     * @mbggenerated
     */
    public void setGjdqdm(String gjdqdm) {
        this.gjdqdm = gjdqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.BYYX
     *
     * @return the value of T_YJS.BYYX
     *
     * @mbggenerated
     */
    public String getByyx() {
        return byyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.BYYX
     *
     * @param byyx the value for T_YJS.BYYX
     *
     * @mbggenerated
     */
    public void setByyx(String byyx) {
        this.byyx = byyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.BYZYDM
     *
     * @return the value of T_YJS.BYZYDM
     *
     * @mbggenerated
     */
    public String getByzydm() {
        return byzydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.BYZYDM
     *
     * @param byzydm the value for T_YJS.BYZYDM
     *
     * @mbggenerated
     */
    public void setByzydm(String byzydm) {
        this.byzydm = byzydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.ZYDZ
     *
     * @return the value of T_YJS.ZYDZ
     *
     * @mbggenerated
     */
    public String getZydz() {
        return zydz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.ZYDZ
     *
     * @param zydz the value for T_YJS.ZYDZ
     *
     * @mbggenerated
     */
    public void setZydz(String zydz) {
        this.zydz = zydz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.CLRQ
     *
     * @return the value of T_YJS.CLRQ
     *
     * @mbggenerated
     */
    public Date getClrq() {
        return clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.CLRQ
     *
     * @param clrq the value for T_YJS.CLRQ
     *
     * @mbggenerated
     */
    public void setClrq(Date clrq) {
        this.clrq = clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.CZLX
     *
     * @return the value of T_YJS.CZLX
     *
     * @mbggenerated
     */
    public String getCzlx() {
        return czlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.CZLX
     *
     * @param czlx the value for T_YJS.CZLX
     *
     * @mbggenerated
     */
    public void setCzlx(String czlx) {
        this.czlx = czlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.CZZ
     *
     * @return the value of T_YJS.CZZ
     *
     * @mbggenerated
     */
    public String getCzz() {
        return czz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.CZZ
     *
     * @param czz the value for T_YJS.CZZ
     *
     * @mbggenerated
     */
    public void setCzz(String czz) {
        this.czz = czz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.BY1
     *
     * @return the value of T_YJS.BY1
     *
     * @mbggenerated
     */
    public String getBy1() {
        return by1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.BY1
     *
     * @param by1 the value for T_YJS.BY1
     *
     * @mbggenerated
     */
    public void setBy1(String by1) {
        this.by1 = by1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XQ
     *
     * @return the value of T_YJS.XQ
     *
     * @mbggenerated
     */
    public String getXq() {
        return xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XQ
     *
     * @param xq the value for T_YJS.XQ
     *
     * @mbggenerated
     */
    public void setXq(String xq) {
        this.xq = xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.HKSZD
     *
     * @return the value of T_YJS.HKSZD
     *
     * @mbggenerated
     */
    public String getHkszd() {
        return hkszd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.HKSZD
     *
     * @param hkszd the value for T_YJS.HKSZD
     *
     * @mbggenerated
     */
    public void setHkszd(String hkszd) {
        this.hkszd = hkszd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.YXDM
     *
     * @return the value of T_YJS.YXDM
     *
     * @mbggenerated
     */
    public String getCollegeCode() {
        return collegeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.YXDM
     *
     * @param collegeCode the value for T_YJS.YXDM
     *
     * @mbggenerated
     */
    public void setCollegeCode(String collegeCode) {
        this.collegeCode = collegeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SFZJLXM
     *
     * @return the value of T_YJS.SFZJLXM
     *
     * @mbggenerated
     */
    public String getSfzjlxm() {
        return sfzjlxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SFZJLXM
     *
     * @param sfzjlxm the value for T_YJS.SFZJLXM
     *
     * @mbggenerated
     */
    public void setSfzjlxm(String sfzjlxm) {
        this.sfzjlxm = sfzjlxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.RXZYDM
     *
     * @return the value of T_YJS.RXZYDM
     *
     * @mbggenerated
     */
    public String getRxzydm() {
        return rxzydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.RXZYDM
     *
     * @param rxzydm the value for T_YJS.RXZYDM
     *
     * @mbggenerated
     */
    public void setRxzydm(String rxzydm) {
        this.rxzydm = rxzydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XKMLDM
     *
     * @return the value of T_YJS.XKMLDM
     *
     * @mbggenerated
     */
    public String getXkmldm() {
        return xkmldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XKMLDM
     *
     * @param xkmldm the value for T_YJS.XKMLDM
     *
     * @mbggenerated
     */
    public void setXkmldm(String xkmldm) {
        this.xkmldm = xkmldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XXFSDM
     *
     * @return the value of T_YJS.XXFSDM
     *
     * @mbggenerated
     */
    public String getXxfsdm() {
        return xxfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XXFSDM
     *
     * @param xxfsdm the value for T_YJS.XXFSDM
     *
     * @mbggenerated
     */
    public void setXxfsdm(String xxfsdm) {
        this.xxfsdm = xxfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.PYFSDM
     *
     * @return the value of T_YJS.PYFSDM
     *
     * @mbggenerated
     */
    public String getPyfsdm() {
        return pyfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.PYFSDM
     *
     * @param pyfsdm the value for T_YJS.PYFSDM
     *
     * @mbggenerated
     */
    public void setPyfsdm(String pyfsdm) {
        this.pyfsdm = pyfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XSLBDM
     *
     * @return the value of T_YJS.XSLBDM
     *
     * @mbggenerated
     */
    public String getXslbdm() {
        return xslbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XSLBDM
     *
     * @param xslbdm the value for T_YJS.XSLBDM
     *
     * @mbggenerated
     */
    public void setXslbdm(String xslbdm) {
        this.xslbdm = xslbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.YJFX
     *
     * @return the value of T_YJS.YJFX
     *
     * @mbggenerated
     */
    public String getYjfx() {
        return yjfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.YJFX
     *
     * @param yjfx the value for T_YJS.YJFX
     *
     * @mbggenerated
     */
    public void setYjfx(String yjfx) {
        this.yjfx = yjfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SFZZS
     *
     * @return the value of T_YJS.SFZZS
     *
     * @mbggenerated
     */
    public String getSfzzs() {
        return sfzzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SFZZS
     *
     * @param sfzzs the value for T_YJS.SFZZS
     *
     * @mbggenerated
     */
    public void setSfzzs(String sfzzs) {
        this.sfzzs = sfzzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.ZZGH
     *
     * @return the value of T_YJS.ZZGH
     *
     * @mbggenerated
     */
    public String getZzgh() {
        return zzgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.ZZGH
     *
     * @param zzgh the value for T_YJS.ZZGH
     *
     * @mbggenerated
     */
    public void setZzgh(String zzgh) {
        this.zzgh = zzgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.DSZGH
     *
     * @return the value of T_YJS.DSZGH
     *
     * @mbggenerated
     */
    public String getDszgh() {
        return dszgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.DSZGH
     *
     * @param dszgh the value for T_YJS.DSZGH
     *
     * @mbggenerated
     */
    public void setDszgh(String dszgh) {
        this.dszgh = dszgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SYDDM
     *
     * @return the value of T_YJS.SYDDM
     *
     * @mbggenerated
     */
    public String getSyddm() {
        return syddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SYDDM
     *
     * @param syddm the value for T_YJS.SYDDM
     *
     * @mbggenerated
     */
    public void setSyddm(String syddm) {
        this.syddm = syddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.HSSBKDM
     *
     * @return the value of T_YJS.HSSBKDM
     *
     * @mbggenerated
     */
    public String getHssbkdm() {
        return hssbkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.HSSBKDM
     *
     * @param hssbkdm the value for T_YJS.HSSBKDM
     *
     * @mbggenerated
     */
    public void setHssbkdm(String hssbkdm) {
        this.hssbkdm = hssbkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XSLYDM
     *
     * @return the value of T_YJS.XSLYDM
     *
     * @mbggenerated
     */
    public String getXslydm() {
        return xslydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XSLYDM
     *
     * @param xslydm the value for T_YJS.XSLYDM
     *
     * @mbggenerated
     */
    public void setXslydm(String xslydm) {
        this.xslydm = xslydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.WTPYDW
     *
     * @return the value of T_YJS.WTPYDW
     *
     * @mbggenerated
     */
    public String getWtpydw() {
        return wtpydw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.WTPYDW
     *
     * @param wtpydw the value for T_YJS.WTPYDW
     *
     * @mbggenerated
     */
    public void setWtpydw(String wtpydw) {
        this.wtpydw = wtpydw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.PYCCDM
     *
     * @return the value of T_YJS.PYCCDM
     *
     * @mbggenerated
     */
    public String getPyccdm() {
        return pyccdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.PYCCDM
     *
     * @param pyccdm the value for T_YJS.PYCCDM
     *
     * @mbggenerated
     */
    public void setPyccdm(String pyccdm) {
        this.pyccdm = pyccdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.RXNJ
     *
     * @return the value of T_YJS.RXNJ
     *
     * @mbggenerated
     */
    public String getRxnj() {
        return rxnj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.RXNJ
     *
     * @param rxnj the value for T_YJS.RXNJ
     *
     * @mbggenerated
     */
    public void setRxnj(String rxnj) {
        this.rxnj = rxnj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XZNJ
     *
     * @return the value of T_YJS.XZNJ
     *
     * @mbggenerated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XZNJ
     *
     * @param grade the value for T_YJS.XZNJ
     *
     * @mbggenerated
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.HDXLFSDM
     *
     * @return the value of T_YJS.HDXLFSDM
     *
     * @mbggenerated
     */
    public String getHdxlfsdm() {
        return hdxlfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.HDXLFSDM
     *
     * @param hdxlfsdm the value for T_YJS.HDXLFSDM
     *
     * @mbggenerated
     */
    public void setHdxlfsdm(String hdxlfsdm) {
        this.hdxlfsdm = hdxlfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XZZYDM
     *
     * @return the value of T_YJS.XZZYDM
     *
     * @mbggenerated
     */
    public String getXzzydm() {
        return xzzydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XZZYDM
     *
     * @param xzzydm the value for T_YJS.XZZYDM
     *
     * @mbggenerated
     */
    public void setXzzydm(String xzzydm) {
        this.xzzydm = xzzydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.BH
     *
     * @return the value of T_YJS.BH
     *
     * @mbggenerated
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.BH
     *
     * @param bh the value for T_YJS.BH
     *
     * @mbggenerated
     */
    public void setBh(String bh) {
        this.bh = bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XZ
     *
     * @return the value of T_YJS.XZ
     *
     * @mbggenerated
     */
    public BigDecimal getXz() {
        return xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XZ
     *
     * @param xz the value for T_YJS.XZ
     *
     * @mbggenerated
     */
    public void setXz(BigDecimal xz) {
        this.xz = xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.DYWYYZ
     *
     * @return the value of T_YJS.DYWYYZ
     *
     * @mbggenerated
     */
    public String getDywyyz() {
        return dywyyz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.DYWYYZ
     *
     * @param dywyyz the value for T_YJS.DYWYYZ
     *
     * @mbggenerated
     */
    public void setDywyyz(String dywyyz) {
        this.dywyyz = dywyyz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.HKXZDM
     *
     * @return the value of T_YJS.HKXZDM
     *
     * @mbggenerated
     */
    public String getHkxzdm() {
        return hkxzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.HKXZDM
     *
     * @param hkxzdm the value for T_YJS.HKXZDM
     *
     * @mbggenerated
     */
    public void setHkxzdm(String hkxzdm) {
        this.hkxzdm = hkxzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.DYWYSP
     *
     * @return the value of T_YJS.DYWYSP
     *
     * @mbggenerated
     */
    public String getDywysp() {
        return dywysp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.DYWYSP
     *
     * @param dywysp the value for T_YJS.DYWYSP
     *
     * @mbggenerated
     */
    public void setDywysp(String dywysp) {
        this.dywysp = dywysp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.DEWYYZ
     *
     * @return the value of T_YJS.DEWYYZ
     *
     * @mbggenerated
     */
    public String getDewyyz() {
        return dewyyz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.DEWYYZ
     *
     * @param dewyyz the value for T_YJS.DEWYYZ
     *
     * @mbggenerated
     */
    public void setDewyyz(String dewyyz) {
        this.dewyyz = dewyyz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.DEWYSP
     *
     * @return the value of T_YJS.DEWYSP
     *
     * @mbggenerated
     */
    public String getDewysp() {
        return dewysp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.DEWYSP
     *
     * @param dewysp the value for T_YJS.DEWYSP
     *
     * @mbggenerated
     */
    public void setDewysp(String dewysp) {
        this.dewysp = dewysp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.JDXWDM
     *
     * @return the value of T_YJS.JDXWDM
     *
     * @mbggenerated
     */
    public String getJdxwdm() {
        return jdxwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.JDXWDM
     *
     * @param jdxwdm the value for T_YJS.JDXWDM
     *
     * @mbggenerated
     */
    public void setJdxwdm(String jdxwdm) {
        this.jdxwdm = jdxwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.JDXLDM
     *
     * @return the value of T_YJS.JDXLDM
     *
     * @mbggenerated
     */
    public String getJdxldm() {
        return jdxldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.JDXLDM
     *
     * @param jdxldm the value for T_YJS.JDXLDM
     *
     * @mbggenerated
     */
    public void setJdxldm(String jdxldm) {
        this.jdxldm = jdxldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XJZT
     *
     * @return the value of T_YJS.XJZT
     *
     * @mbggenerated
     */
    public String getXjzt() {
        return xjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XJZT
     *
     * @param xjzt the value for T_YJS.XJZT
     *
     * @mbggenerated
     */
    public void setXjzt(String xjzt) {
        this.xjzt = xjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.ZCQK
     *
     * @return the value of T_YJS.ZCQK
     *
     * @mbggenerated
     */
    public String getRegisterInfo() {
        return registerInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.ZCQK
     *
     * @param registerInfo the value for T_YJS.ZCQK
     *
     * @mbggenerated
     */
    public void setRegisterInfo(String registerInfo) {
        this.registerInfo = registerInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.YJBYNF
     *
     * @return the value of T_YJS.YJBYNF
     *
     * @mbggenerated
     */
    public String getYjbynf() {
        return yjbynf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.YJBYNF
     *
     * @param yjbynf the value for T_YJS.YJBYNF
     *
     * @mbggenerated
     */
    public void setYjbynf(String yjbynf) {
        this.yjbynf = yjbynf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.YJBYJD
     *
     * @return the value of T_YJS.YJBYJD
     *
     * @mbggenerated
     */
    public String getYjbyjd() {
        return yjbyjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.YJBYJD
     *
     * @param yjbyjd the value for T_YJS.YJBYJD
     *
     * @mbggenerated
     */
    public void setYjbyjd(String yjbyjd) {
        this.yjbyjd = yjbyjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.ZHCP
     *
     * @return the value of T_YJS.ZHCP
     *
     * @mbggenerated
     */
    public String getZhcp() {
        return zhcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.ZHCP
     *
     * @param zhcp the value for T_YJS.ZHCP
     *
     * @mbggenerated
     */
    public void setZhcp(String zhcp) {
        this.zhcp = zhcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SG
     *
     * @return the value of T_YJS.SG
     *
     * @mbggenerated
     */
    public BigDecimal getSg() {
        return sg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SG
     *
     * @param sg the value for T_YJS.SG
     *
     * @mbggenerated
     */
    public void setSg(BigDecimal sg) {
        this.sg = sg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XWLXDM
     *
     * @return the value of T_YJS.XWLXDM
     *
     * @mbggenerated
     */
    public String getXwlxdm() {
        return xwlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XWLXDM
     *
     * @param xwlxdm the value for T_YJS.XWLXDM
     *
     * @mbggenerated
     */
    public void setXwlxdm(String xwlxdm) {
        this.xwlxdm = xwlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.TZ
     *
     * @return the value of T_YJS.TZ
     *
     * @mbggenerated
     */
    public BigDecimal getTz() {
        return tz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.TZ
     *
     * @param tz the value for T_YJS.TZ
     *
     * @mbggenerated
     */
    public void setTz(BigDecimal tz) {
        this.tz = tz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SJBYSJ
     *
     * @return the value of T_YJS.SJBYSJ
     *
     * @mbggenerated
     */
    public String getSjbysj() {
        return sjbysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SJBYSJ
     *
     * @param sjbysj the value for T_YJS.SJBYSJ
     *
     * @mbggenerated
     */
    public void setSjbysj(String sjbysj) {
        this.sjbysj = sjbysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.RXNY
     *
     * @return the value of T_YJS.RXNY
     *
     * @mbggenerated
     */
    public String getRxny() {
        return rxny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.RXNY
     *
     * @param rxny the value for T_YJS.RXNY
     *
     * @mbggenerated
     */
    public void setRxny(String rxny) {
        this.rxny = rxny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SJLY
     *
     * @return the value of T_YJS.SJLY
     *
     * @mbggenerated
     */
    public String getSjly() {
        return sjly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SJLY
     *
     * @param sjly the value for T_YJS.SJLY
     *
     * @mbggenerated
     */
    public void setSjly(String sjly) {
        this.sjly = sjly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.DQZTDM
     *
     * @return the value of T_YJS.DQZTDM
     *
     * @mbggenerated
     */
    public String getDqztdm() {
        return dqztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.DQZTDM
     *
     * @param dqztdm the value for T_YJS.DQZTDM
     *
     * @mbggenerated
     */
    public void setDqztdm(String dqztdm) {
        this.dqztdm = dqztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SFZX
     *
     * @return the value of T_YJS.SFZX
     *
     * @mbggenerated
     */
    public String getSfzx() {
        return sfzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SFZX
     *
     * @param sfzx the value for T_YJS.SFZX
     *
     * @mbggenerated
     */
    public void setSfzx(String sfzx) {
        this.sfzx = sfzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SJBBH
     *
     * @return the value of T_YJS.SJBBH
     *
     * @mbggenerated
     */
    public String getSjbbh() {
        return sjbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SJBBH
     *
     * @param sjbbh the value for T_YJS.SJBBH
     *
     * @mbggenerated
     */
    public void setSjbbh(String sjbbh) {
        this.sjbbh = sjbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SFXFZ
     *
     * @return the value of T_YJS.SFXFZ
     *
     * @mbggenerated
     */
    public String getSfxfz() {
        return sfxfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SFXFZ
     *
     * @param sfxfz the value for T_YJS.SFXFZ
     *
     * @mbggenerated
     */
    public void setSfxfz(String sfxfz) {
        this.sfxfz = sfxfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.LDFSDM
     *
     * @return the value of T_YJS.LDFSDM
     *
     * @mbggenerated
     */
    public String getLdfsdm() {
        return ldfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.LDFSDM
     *
     * @param ldfsdm the value for T_YJS.LDFSDM
     *
     * @mbggenerated
     */
    public void setLdfsdm(String ldfsdm) {
        this.ldfsdm = ldfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.GATQWDM
     *
     * @return the value of T_YJS.GATQWDM
     *
     * @mbggenerated
     */
    public String getGatqwdm() {
        return gatqwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.GATQWDM
     *
     * @param gatqwdm the value for T_YJS.GATQWDM
     *
     * @mbggenerated
     */
    public void setGatqwdm(String gatqwdm) {
        this.gatqwdm = gatqwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.XYZJDM
     *
     * @return the value of T_YJS.XYZJDM
     *
     * @mbggenerated
     */
    public String getXyzjdm() {
        return xyzjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.XYZJDM
     *
     * @param xyzjdm the value for T_YJS.XYZJDM
     *
     * @mbggenerated
     */
    public void setXyzjdm(String xyzjdm) {
        this.xyzjdm = xyzjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SFZJYXKSQ
     *
     * @return the value of T_YJS.SFZJYXKSQ
     *
     * @mbggenerated
     */
    public String getSfzjyxksq() {
        return sfzjyxksq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SFZJYXKSQ
     *
     * @param sfzjyxksq the value for T_YJS.SFZJYXKSQ
     *
     * @mbggenerated
     */
    public void setSfzjyxksq(String sfzjyxksq) {
        this.sfzjyxksq = sfzjyxksq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SFZJYXJZQ
     *
     * @return the value of T_YJS.SFZJYXJZQ
     *
     * @mbggenerated
     */
    public String getSfzjyxjzq() {
        return sfzjyxjzq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SFZJYXJZQ
     *
     * @param sfzjyxjzq the value for T_YJS.SFZJYXJZQ
     *
     * @mbggenerated
     */
    public void setSfzjyxjzq(String sfzjyxjzq) {
        this.sfzjyxjzq = sfzjyxjzq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SFDSZN
     *
     * @return the value of T_YJS.SFDSZN
     *
     * @mbggenerated
     */
    public String getSfdszn() {
        return sfdszn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SFDSZN
     *
     * @param sfdszn the value for T_YJS.SFDSZN
     *
     * @mbggenerated
     */
    public void setSfdszn(String sfdszn) {
        this.sfdszn = sfdszn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.YXH
     *
     * @return the value of T_YJS.YXH
     *
     * @mbggenerated
     */
    public String getYxh() {
        return yxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.YXH
     *
     * @param yxh the value for T_YJS.YXH
     *
     * @mbggenerated
     */
    public void setYxh(String yxh) {
        this.yxh = yxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.LYDQDM
     *
     * @return the value of T_YJS.LYDQDM
     *
     * @mbggenerated
     */
    public String getLydqdm() {
        return lydqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.LYDQDM
     *
     * @param lydqdm the value for T_YJS.LYDQDM
     *
     * @mbggenerated
     */
    public void setLydqdm(String lydqdm) {
        this.lydqdm = lydqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.JG
     *
     * @return the value of T_YJS.JG
     *
     * @mbggenerated
     */
    public String getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.JG
     *
     * @param jg the value for T_YJS.JG
     *
     * @mbggenerated
     */
    public void setJg(String jg) {
        this.jg = jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SFZJYXQ
     *
     * @return the value of T_YJS.SFZJYXQ
     *
     * @mbggenerated
     */
    public String getSfzjyxq() {
        return sfzjyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SFZJYXQ
     *
     * @param sfzjyxq the value for T_YJS.SFZJYXQ
     *
     * @mbggenerated
     */
    public void setSfzjyxq(String sfzjyxq) {
        this.sfzjyxq = sfzjyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SFBY
     *
     * @return the value of T_YJS.SFBY
     *
     * @mbggenerated
     */
    public String getSfby() {
        return sfby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SFBY
     *
     * @param sfby the value for T_YJS.SFBY
     *
     * @mbggenerated
     */
    public void setSfby(String sfby) {
        this.sfby = sfby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SS
     *
     * @return the value of T_YJS.SS
     *
     * @mbggenerated
     */
    public String getSs() {
        return ss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SS
     *
     * @param ss the value for T_YJS.SS
     *
     * @mbggenerated
     */
    public void setSs(String ss) {
        this.ss = ss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.SSDH
     *
     * @return the value of T_YJS.SSDH
     *
     * @mbggenerated
     */
    public String getSsdh() {
        return ssdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.SSDH
     *
     * @param ssdh the value for T_YJS.SSDH
     *
     * @mbggenerated
     */
    public void setSsdh(String ssdh) {
        this.ssdh = ssdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.GRDH
     *
     * @return the value of T_YJS.GRDH
     *
     * @mbggenerated
     */
    public String getGrdh() {
        return grdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.GRDH
     *
     * @param grdh the value for T_YJS.GRDH
     *
     * @mbggenerated
     */
    public void setGrdh(String grdh) {
        this.grdh = grdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_YJS.EMAIL
     *
     * @return the value of T_YJS.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_YJS.EMAIL
     *
     * @param email the value for T_YJS.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }
}