package com.buptyouth.mybatis.model;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_id
     *
     * @mbggenerated
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_name
     *
     * @mbggenerated
     */
    private String roomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.audio
     *
     * @mbggenerated
     */
    private String audio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.projector
     *
     * @mbggenerated
     */
    private String projector;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_id
     *
     * @return the value of room.room_id
     *
     * @mbggenerated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_id
     *
     * @param roomId the value for room.room_id
     *
     * @mbggenerated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_name
     *
     * @return the value of room.room_name
     *
     * @mbggenerated
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_name
     *
     * @param roomName the value for room.room_name
     *
     * @mbggenerated
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.audio
     *
     * @return the value of room.audio
     *
     * @mbggenerated
     */
    public String getAudio() {
        return audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.audio
     *
     * @param audio the value for room.audio
     *
     * @mbggenerated
     */
    public void setAudio(String audio) {
        this.audio = audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.projector
     *
     * @return the value of room.projector
     *
     * @mbggenerated
     */
    public String getProjector() {
        return projector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.projector
     *
     * @param projector the value for room.projector
     *
     * @mbggenerated
     */
    public void setProjector(String projector) {
        this.projector = projector;
    }
}