package com.buptyouth.mybatis.model;

import java.util.Date;

public class Schoolcalendar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolcalendar.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolcalendar.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolcalendar.date
     *
     * @return the value of schoolcalendar.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolcalendar.date
     *
     * @param date the value for schoolcalendar.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolcalendar.state
     *
     * @return the value of schoolcalendar.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolcalendar.state
     *
     * @param state the value for schoolcalendar.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}