package com.buptyouth.mybatis.model;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.WID
     *
     * @mbggenerated
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.ZGH
     *
     * @mbggenerated
     */
    private String staffNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XM
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XMPY
     *
     * @mbggenerated
     */
    private String xmpy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.CYM
     *
     * @mbggenerated
     */
    private String cym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.SFZJLXM
     *
     * @mbggenerated
     */
    private String sfzjlxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.SFZJH
     *
     * @mbggenerated
     */
    private String sfzjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.CSRQ
     *
     * @mbggenerated
     */
    private String csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XBDM
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.MZDM
     *
     * @mbggenerated
     */
    private String mzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.ZZMMDM
     *
     * @mbggenerated
     */
    private String zzmmdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.DEZZMMDM
     *
     * @mbggenerated
     */
    private String dezzmmdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.JKZKDM
     *
     * @mbggenerated
     */
    private String jkzkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XXDM
     *
     * @mbggenerated
     */
    private String xxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.ZJXYDM
     *
     * @mbggenerated
     */
    private String zjxydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.GJDQDM
     *
     * @mbggenerated
     */
    private String gjdqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.GATQDM
     *
     * @mbggenerated
     */
    private String gatqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.HYZKDM
     *
     * @mbggenerated
     */
    private String hyzkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.JGDM
     *
     * @mbggenerated
     */
    private String jgdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.CSDDM
     *
     * @mbggenerated
     */
    private String csddm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.JTCSDM
     *
     * @mbggenerated
     */
    private String jtcsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.BRCFDM
     *
     * @mbggenerated
     */
    private String brcfdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.WHCDDM
     *
     * @mbggenerated
     */
    private String whcddm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XWDM
     *
     * @mbggenerated
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.TC
     *
     * @mbggenerated
     */
    private String tc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.CLRQ
     *
     * @mbggenerated
     */
    private String clrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.CZLX
     *
     * @mbggenerated
     */
    private String czlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.CZZ
     *
     * @mbggenerated
     */
    private String czz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.BY1
     *
     * @mbggenerated
     */
    private String by1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.BY2
     *
     * @mbggenerated
     */
    private String by2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.DWDM
     *
     * @mbggenerated
     */
    private String dwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XQDM
     *
     * @mbggenerated
     */
    private String xqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.CJGZRQ
     *
     * @mbggenerated
     */
    private String cjgzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.RDRQ
     *
     * @mbggenerated
     */
    private String rdrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.LXNY
     *
     * @mbggenerated
     */
    private String lxny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XCSZY
     *
     * @mbggenerated
     */
    private String xcszy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.CJNY
     *
     * @mbggenerated
     */
    private String cjny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.BZLBDM
     *
     * @mbggenerated
     */
    private String bzlbdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.JZGLBDM
     *
     * @mbggenerated
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.RKZKDM
     *
     * @mbggenerated
     */
    private String rkzkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.DABH
     *
     * @mbggenerated
     */
    private String dabh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.ZWLBDM
     *
     * @mbggenerated
     */
    private String zwlbdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XZJBDM
     *
     * @mbggenerated
     */
    private String xzjbdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.ZYJSZWDM
     *
     * @mbggenerated
     */
    private String zyjszwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.GRJSDJDM
     *
     * @mbggenerated
     */
    private String grjsdjdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.YPCSZY
     *
     * @mbggenerated
     */
    private String ypcszy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XKDM
     *
     * @mbggenerated
     */
    private String xkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XKDM2
     *
     * @mbggenerated
     */
    private String xkdm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XKDM3
     *
     * @mbggenerated
     */
    private String xkdm3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.GW
     *
     * @mbggenerated
     */
    private String gw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.ZBQK
     *
     * @mbggenerated
     */
    private String zbqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.DQZTDM
     *
     * @mbggenerated
     */
    private String dqztdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.DAWB
     *
     * @mbggenerated
     */
    private String dawb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.DYWYYZDM
     *
     * @mbggenerated
     */
    private String dywyyzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.DYWYSPDM
     *
     * @mbggenerated
     */
    private String dywyspdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.DEWYYZDM
     *
     * @mbggenerated
     */
    private String dewyyzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.DEWYSPDM
     *
     * @mbggenerated
     */
    private String dewyspdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.SJLY
     *
     * @mbggenerated
     */
    private String dataResource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.YPYJXK
     *
     * @mbggenerated
     */
    private String ypyjxk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.XYJXK
     *
     * @mbggenerated
     */
    private String xyjxk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.SJBBH
     *
     * @mbggenerated
     */
    private String sjbbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.YWXM
     *
     * @mbggenerated
     */
    private String ywxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.SFZJYXQ
     *
     * @mbggenerated
     */
    private String sfzjyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.QXRQ
     *
     * @mbggenerated
     */
    private String qxrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.JG
     *
     * @mbggenerated
     */
    private String jg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.ZGXLM
     *
     * @mbggenerated
     */
    private String zgxlm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.BGDZ
     *
     * @mbggenerated
     */
    private String bgdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.BGDH
     *
     * @mbggenerated
     */
    private String bgdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.GRDH
     *
     * @mbggenerated
     */
    private String grdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.SFZX
     *
     * @mbggenerated
     */
    private Short sfzx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JZG.PX
     *
     * @mbggenerated
     */
    private String px;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.WID
     *
     * @return the value of T_JZG.WID
     *
     * @mbggenerated
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.WID
     *
     * @param wid the value for T_JZG.WID
     *
     * @mbggenerated
     */
    public void setWid(String wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.ZGH
     *
     * @return the value of T_JZG.ZGH
     *
     * @mbggenerated
     */
    public String getStaffNumber() {
        return staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.ZGH
     *
     * @param staffNumber the value for T_JZG.ZGH
     *
     * @mbggenerated
     */
    public void setStaffNumber(String staffNumber) {
        this.staffNumber = staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XM
     *
     * @return the value of T_JZG.XM
     *
     * @mbggenerated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XM
     *
     * @param staffName the value for T_JZG.XM
     *
     * @mbggenerated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XMPY
     *
     * @return the value of T_JZG.XMPY
     *
     * @mbggenerated
     */
    public String getXmpy() {
        return xmpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XMPY
     *
     * @param xmpy the value for T_JZG.XMPY
     *
     * @mbggenerated
     */
    public void setXmpy(String xmpy) {
        this.xmpy = xmpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.CYM
     *
     * @return the value of T_JZG.CYM
     *
     * @mbggenerated
     */
    public String getCym() {
        return cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.CYM
     *
     * @param cym the value for T_JZG.CYM
     *
     * @mbggenerated
     */
    public void setCym(String cym) {
        this.cym = cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.SFZJLXM
     *
     * @return the value of T_JZG.SFZJLXM
     *
     * @mbggenerated
     */
    public String getSfzjlxm() {
        return sfzjlxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.SFZJLXM
     *
     * @param sfzjlxm the value for T_JZG.SFZJLXM
     *
     * @mbggenerated
     */
    public void setSfzjlxm(String sfzjlxm) {
        this.sfzjlxm = sfzjlxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.SFZJH
     *
     * @return the value of T_JZG.SFZJH
     *
     * @mbggenerated
     */
    public String getSfzjh() {
        return sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.SFZJH
     *
     * @param sfzjh the value for T_JZG.SFZJH
     *
     * @mbggenerated
     */
    public void setSfzjh(String sfzjh) {
        this.sfzjh = sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.CSRQ
     *
     * @return the value of T_JZG.CSRQ
     *
     * @mbggenerated
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.CSRQ
     *
     * @param csrq the value for T_JZG.CSRQ
     *
     * @mbggenerated
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XBDM
     *
     * @return the value of T_JZG.XBDM
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XBDM
     *
     * @param gender the value for T_JZG.XBDM
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.MZDM
     *
     * @return the value of T_JZG.MZDM
     *
     * @mbggenerated
     */
    public String getMzdm() {
        return mzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.MZDM
     *
     * @param mzdm the value for T_JZG.MZDM
     *
     * @mbggenerated
     */
    public void setMzdm(String mzdm) {
        this.mzdm = mzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.ZZMMDM
     *
     * @return the value of T_JZG.ZZMMDM
     *
     * @mbggenerated
     */
    public String getZzmmdm() {
        return zzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.ZZMMDM
     *
     * @param zzmmdm the value for T_JZG.ZZMMDM
     *
     * @mbggenerated
     */
    public void setZzmmdm(String zzmmdm) {
        this.zzmmdm = zzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.DEZZMMDM
     *
     * @return the value of T_JZG.DEZZMMDM
     *
     * @mbggenerated
     */
    public String getDezzmmdm() {
        return dezzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.DEZZMMDM
     *
     * @param dezzmmdm the value for T_JZG.DEZZMMDM
     *
     * @mbggenerated
     */
    public void setDezzmmdm(String dezzmmdm) {
        this.dezzmmdm = dezzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.JKZKDM
     *
     * @return the value of T_JZG.JKZKDM
     *
     * @mbggenerated
     */
    public String getJkzkdm() {
        return jkzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.JKZKDM
     *
     * @param jkzkdm the value for T_JZG.JKZKDM
     *
     * @mbggenerated
     */
    public void setJkzkdm(String jkzkdm) {
        this.jkzkdm = jkzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XXDM
     *
     * @return the value of T_JZG.XXDM
     *
     * @mbggenerated
     */
    public String getXxdm() {
        return xxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XXDM
     *
     * @param xxdm the value for T_JZG.XXDM
     *
     * @mbggenerated
     */
    public void setXxdm(String xxdm) {
        this.xxdm = xxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.ZJXYDM
     *
     * @return the value of T_JZG.ZJXYDM
     *
     * @mbggenerated
     */
    public String getZjxydm() {
        return zjxydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.ZJXYDM
     *
     * @param zjxydm the value for T_JZG.ZJXYDM
     *
     * @mbggenerated
     */
    public void setZjxydm(String zjxydm) {
        this.zjxydm = zjxydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.GJDQDM
     *
     * @return the value of T_JZG.GJDQDM
     *
     * @mbggenerated
     */
    public String getGjdqdm() {
        return gjdqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.GJDQDM
     *
     * @param gjdqdm the value for T_JZG.GJDQDM
     *
     * @mbggenerated
     */
    public void setGjdqdm(String gjdqdm) {
        this.gjdqdm = gjdqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.GATQDM
     *
     * @return the value of T_JZG.GATQDM
     *
     * @mbggenerated
     */
    public String getGatqdm() {
        return gatqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.GATQDM
     *
     * @param gatqdm the value for T_JZG.GATQDM
     *
     * @mbggenerated
     */
    public void setGatqdm(String gatqdm) {
        this.gatqdm = gatqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.HYZKDM
     *
     * @return the value of T_JZG.HYZKDM
     *
     * @mbggenerated
     */
    public String getHyzkdm() {
        return hyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.HYZKDM
     *
     * @param hyzkdm the value for T_JZG.HYZKDM
     *
     * @mbggenerated
     */
    public void setHyzkdm(String hyzkdm) {
        this.hyzkdm = hyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.JGDM
     *
     * @return the value of T_JZG.JGDM
     *
     * @mbggenerated
     */
    public String getJgdm() {
        return jgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.JGDM
     *
     * @param jgdm the value for T_JZG.JGDM
     *
     * @mbggenerated
     */
    public void setJgdm(String jgdm) {
        this.jgdm = jgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.CSDDM
     *
     * @return the value of T_JZG.CSDDM
     *
     * @mbggenerated
     */
    public String getCsddm() {
        return csddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.CSDDM
     *
     * @param csddm the value for T_JZG.CSDDM
     *
     * @mbggenerated
     */
    public void setCsddm(String csddm) {
        this.csddm = csddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.JTCSDM
     *
     * @return the value of T_JZG.JTCSDM
     *
     * @mbggenerated
     */
    public String getJtcsdm() {
        return jtcsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.JTCSDM
     *
     * @param jtcsdm the value for T_JZG.JTCSDM
     *
     * @mbggenerated
     */
    public void setJtcsdm(String jtcsdm) {
        this.jtcsdm = jtcsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.BRCFDM
     *
     * @return the value of T_JZG.BRCFDM
     *
     * @mbggenerated
     */
    public String getBrcfdm() {
        return brcfdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.BRCFDM
     *
     * @param brcfdm the value for T_JZG.BRCFDM
     *
     * @mbggenerated
     */
    public void setBrcfdm(String brcfdm) {
        this.brcfdm = brcfdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.WHCDDM
     *
     * @return the value of T_JZG.WHCDDM
     *
     * @mbggenerated
     */
    public String getWhcddm() {
        return whcddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.WHCDDM
     *
     * @param whcddm the value for T_JZG.WHCDDM
     *
     * @mbggenerated
     */
    public void setWhcddm(String whcddm) {
        this.whcddm = whcddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XWDM
     *
     * @return the value of T_JZG.XWDM
     *
     * @mbggenerated
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XWDM
     *
     * @param degree the value for T_JZG.XWDM
     *
     * @mbggenerated
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.TC
     *
     * @return the value of T_JZG.TC
     *
     * @mbggenerated
     */
    public String getTc() {
        return tc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.TC
     *
     * @param tc the value for T_JZG.TC
     *
     * @mbggenerated
     */
    public void setTc(String tc) {
        this.tc = tc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.CLRQ
     *
     * @return the value of T_JZG.CLRQ
     *
     * @mbggenerated
     */
    public String getClrq() {
        return clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.CLRQ
     *
     * @param clrq the value for T_JZG.CLRQ
     *
     * @mbggenerated
     */
    public void setClrq(String clrq) {
        this.clrq = clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.CZLX
     *
     * @return the value of T_JZG.CZLX
     *
     * @mbggenerated
     */
    public String getCzlx() {
        return czlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.CZLX
     *
     * @param czlx the value for T_JZG.CZLX
     *
     * @mbggenerated
     */
    public void setCzlx(String czlx) {
        this.czlx = czlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.CZZ
     *
     * @return the value of T_JZG.CZZ
     *
     * @mbggenerated
     */
    public String getCzz() {
        return czz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.CZZ
     *
     * @param czz the value for T_JZG.CZZ
     *
     * @mbggenerated
     */
    public void setCzz(String czz) {
        this.czz = czz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.BY1
     *
     * @return the value of T_JZG.BY1
     *
     * @mbggenerated
     */
    public String getBy1() {
        return by1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.BY1
     *
     * @param by1 the value for T_JZG.BY1
     *
     * @mbggenerated
     */
    public void setBy1(String by1) {
        this.by1 = by1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.BY2
     *
     * @return the value of T_JZG.BY2
     *
     * @mbggenerated
     */
    public String getBy2() {
        return by2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.BY2
     *
     * @param by2 the value for T_JZG.BY2
     *
     * @mbggenerated
     */
    public void setBy2(String by2) {
        this.by2 = by2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.DWDM
     *
     * @return the value of T_JZG.DWDM
     *
     * @mbggenerated
     */
    public String getDwdm() {
        return dwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.DWDM
     *
     * @param dwdm the value for T_JZG.DWDM
     *
     * @mbggenerated
     */
    public void setDwdm(String dwdm) {
        this.dwdm = dwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XQDM
     *
     * @return the value of T_JZG.XQDM
     *
     * @mbggenerated
     */
    public String getXqdm() {
        return xqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XQDM
     *
     * @param xqdm the value for T_JZG.XQDM
     *
     * @mbggenerated
     */
    public void setXqdm(String xqdm) {
        this.xqdm = xqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.CJGZRQ
     *
     * @return the value of T_JZG.CJGZRQ
     *
     * @mbggenerated
     */
    public String getCjgzrq() {
        return cjgzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.CJGZRQ
     *
     * @param cjgzrq the value for T_JZG.CJGZRQ
     *
     * @mbggenerated
     */
    public void setCjgzrq(String cjgzrq) {
        this.cjgzrq = cjgzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.RDRQ
     *
     * @return the value of T_JZG.RDRQ
     *
     * @mbggenerated
     */
    public String getRdrq() {
        return rdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.RDRQ
     *
     * @param rdrq the value for T_JZG.RDRQ
     *
     * @mbggenerated
     */
    public void setRdrq(String rdrq) {
        this.rdrq = rdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.LXNY
     *
     * @return the value of T_JZG.LXNY
     *
     * @mbggenerated
     */
    public String getLxny() {
        return lxny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.LXNY
     *
     * @param lxny the value for T_JZG.LXNY
     *
     * @mbggenerated
     */
    public void setLxny(String lxny) {
        this.lxny = lxny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XCSZY
     *
     * @return the value of T_JZG.XCSZY
     *
     * @mbggenerated
     */
    public String getXcszy() {
        return xcszy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XCSZY
     *
     * @param xcszy the value for T_JZG.XCSZY
     *
     * @mbggenerated
     */
    public void setXcszy(String xcszy) {
        this.xcszy = xcszy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.CJNY
     *
     * @return the value of T_JZG.CJNY
     *
     * @mbggenerated
     */
    public String getCjny() {
        return cjny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.CJNY
     *
     * @param cjny the value for T_JZG.CJNY
     *
     * @mbggenerated
     */
    public void setCjny(String cjny) {
        this.cjny = cjny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.BZLBDM
     *
     * @return the value of T_JZG.BZLBDM
     *
     * @mbggenerated
     */
    public String getBzlbdm() {
        return bzlbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.BZLBDM
     *
     * @param bzlbdm the value for T_JZG.BZLBDM
     *
     * @mbggenerated
     */
    public void setBzlbdm(String bzlbdm) {
        this.bzlbdm = bzlbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.JZGLBDM
     *
     * @return the value of T_JZG.JZGLBDM
     *
     * @mbggenerated
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.JZGLBDM
     *
     * @param classCode the value for T_JZG.JZGLBDM
     *
     * @mbggenerated
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.RKZKDM
     *
     * @return the value of T_JZG.RKZKDM
     *
     * @mbggenerated
     */
    public String getRkzkdm() {
        return rkzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.RKZKDM
     *
     * @param rkzkdm the value for T_JZG.RKZKDM
     *
     * @mbggenerated
     */
    public void setRkzkdm(String rkzkdm) {
        this.rkzkdm = rkzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.DABH
     *
     * @return the value of T_JZG.DABH
     *
     * @mbggenerated
     */
    public String getDabh() {
        return dabh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.DABH
     *
     * @param dabh the value for T_JZG.DABH
     *
     * @mbggenerated
     */
    public void setDabh(String dabh) {
        this.dabh = dabh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.ZWLBDM
     *
     * @return the value of T_JZG.ZWLBDM
     *
     * @mbggenerated
     */
    public String getZwlbdm() {
        return zwlbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.ZWLBDM
     *
     * @param zwlbdm the value for T_JZG.ZWLBDM
     *
     * @mbggenerated
     */
    public void setZwlbdm(String zwlbdm) {
        this.zwlbdm = zwlbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XZJBDM
     *
     * @return the value of T_JZG.XZJBDM
     *
     * @mbggenerated
     */
    public String getXzjbdm() {
        return xzjbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XZJBDM
     *
     * @param xzjbdm the value for T_JZG.XZJBDM
     *
     * @mbggenerated
     */
    public void setXzjbdm(String xzjbdm) {
        this.xzjbdm = xzjbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.ZYJSZWDM
     *
     * @return the value of T_JZG.ZYJSZWDM
     *
     * @mbggenerated
     */
    public String getZyjszwdm() {
        return zyjszwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.ZYJSZWDM
     *
     * @param zyjszwdm the value for T_JZG.ZYJSZWDM
     *
     * @mbggenerated
     */
    public void setZyjszwdm(String zyjszwdm) {
        this.zyjszwdm = zyjszwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.GRJSDJDM
     *
     * @return the value of T_JZG.GRJSDJDM
     *
     * @mbggenerated
     */
    public String getGrjsdjdm() {
        return grjsdjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.GRJSDJDM
     *
     * @param grjsdjdm the value for T_JZG.GRJSDJDM
     *
     * @mbggenerated
     */
    public void setGrjsdjdm(String grjsdjdm) {
        this.grjsdjdm = grjsdjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.YPCSZY
     *
     * @return the value of T_JZG.YPCSZY
     *
     * @mbggenerated
     */
    public String getYpcszy() {
        return ypcszy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.YPCSZY
     *
     * @param ypcszy the value for T_JZG.YPCSZY
     *
     * @mbggenerated
     */
    public void setYpcszy(String ypcszy) {
        this.ypcszy = ypcszy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XKDM
     *
     * @return the value of T_JZG.XKDM
     *
     * @mbggenerated
     */
    public String getXkdm() {
        return xkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XKDM
     *
     * @param xkdm the value for T_JZG.XKDM
     *
     * @mbggenerated
     */
    public void setXkdm(String xkdm) {
        this.xkdm = xkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XKDM2
     *
     * @return the value of T_JZG.XKDM2
     *
     * @mbggenerated
     */
    public String getXkdm2() {
        return xkdm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XKDM2
     *
     * @param xkdm2 the value for T_JZG.XKDM2
     *
     * @mbggenerated
     */
    public void setXkdm2(String xkdm2) {
        this.xkdm2 = xkdm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XKDM3
     *
     * @return the value of T_JZG.XKDM3
     *
     * @mbggenerated
     */
    public String getXkdm3() {
        return xkdm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XKDM3
     *
     * @param xkdm3 the value for T_JZG.XKDM3
     *
     * @mbggenerated
     */
    public void setXkdm3(String xkdm3) {
        this.xkdm3 = xkdm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.GW
     *
     * @return the value of T_JZG.GW
     *
     * @mbggenerated
     */
    public String getGw() {
        return gw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.GW
     *
     * @param gw the value for T_JZG.GW
     *
     * @mbggenerated
     */
    public void setGw(String gw) {
        this.gw = gw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.ZBQK
     *
     * @return the value of T_JZG.ZBQK
     *
     * @mbggenerated
     */
    public String getZbqk() {
        return zbqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.ZBQK
     *
     * @param zbqk the value for T_JZG.ZBQK
     *
     * @mbggenerated
     */
    public void setZbqk(String zbqk) {
        this.zbqk = zbqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.DQZTDM
     *
     * @return the value of T_JZG.DQZTDM
     *
     * @mbggenerated
     */
    public String getDqztdm() {
        return dqztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.DQZTDM
     *
     * @param dqztdm the value for T_JZG.DQZTDM
     *
     * @mbggenerated
     */
    public void setDqztdm(String dqztdm) {
        this.dqztdm = dqztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.DAWB
     *
     * @return the value of T_JZG.DAWB
     *
     * @mbggenerated
     */
    public String getDawb() {
        return dawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.DAWB
     *
     * @param dawb the value for T_JZG.DAWB
     *
     * @mbggenerated
     */
    public void setDawb(String dawb) {
        this.dawb = dawb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.DYWYYZDM
     *
     * @return the value of T_JZG.DYWYYZDM
     *
     * @mbggenerated
     */
    public String getDywyyzdm() {
        return dywyyzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.DYWYYZDM
     *
     * @param dywyyzdm the value for T_JZG.DYWYYZDM
     *
     * @mbggenerated
     */
    public void setDywyyzdm(String dywyyzdm) {
        this.dywyyzdm = dywyyzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.DYWYSPDM
     *
     * @return the value of T_JZG.DYWYSPDM
     *
     * @mbggenerated
     */
    public String getDywyspdm() {
        return dywyspdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.DYWYSPDM
     *
     * @param dywyspdm the value for T_JZG.DYWYSPDM
     *
     * @mbggenerated
     */
    public void setDywyspdm(String dywyspdm) {
        this.dywyspdm = dywyspdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.DEWYYZDM
     *
     * @return the value of T_JZG.DEWYYZDM
     *
     * @mbggenerated
     */
    public String getDewyyzdm() {
        return dewyyzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.DEWYYZDM
     *
     * @param dewyyzdm the value for T_JZG.DEWYYZDM
     *
     * @mbggenerated
     */
    public void setDewyyzdm(String dewyyzdm) {
        this.dewyyzdm = dewyyzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.DEWYSPDM
     *
     * @return the value of T_JZG.DEWYSPDM
     *
     * @mbggenerated
     */
    public String getDewyspdm() {
        return dewyspdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.DEWYSPDM
     *
     * @param dewyspdm the value for T_JZG.DEWYSPDM
     *
     * @mbggenerated
     */
    public void setDewyspdm(String dewyspdm) {
        this.dewyspdm = dewyspdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.SJLY
     *
     * @return the value of T_JZG.SJLY
     *
     * @mbggenerated
     */
    public String getDataResource() {
        return dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.SJLY
     *
     * @param dataResource the value for T_JZG.SJLY
     *
     * @mbggenerated
     */
    public void setDataResource(String dataResource) {
        this.dataResource = dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.YPYJXK
     *
     * @return the value of T_JZG.YPYJXK
     *
     * @mbggenerated
     */
    public String getYpyjxk() {
        return ypyjxk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.YPYJXK
     *
     * @param ypyjxk the value for T_JZG.YPYJXK
     *
     * @mbggenerated
     */
    public void setYpyjxk(String ypyjxk) {
        this.ypyjxk = ypyjxk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.XYJXK
     *
     * @return the value of T_JZG.XYJXK
     *
     * @mbggenerated
     */
    public String getXyjxk() {
        return xyjxk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.XYJXK
     *
     * @param xyjxk the value for T_JZG.XYJXK
     *
     * @mbggenerated
     */
    public void setXyjxk(String xyjxk) {
        this.xyjxk = xyjxk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.SJBBH
     *
     * @return the value of T_JZG.SJBBH
     *
     * @mbggenerated
     */
    public String getSjbbh() {
        return sjbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.SJBBH
     *
     * @param sjbbh the value for T_JZG.SJBBH
     *
     * @mbggenerated
     */
    public void setSjbbh(String sjbbh) {
        this.sjbbh = sjbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.YWXM
     *
     * @return the value of T_JZG.YWXM
     *
     * @mbggenerated
     */
    public String getYwxm() {
        return ywxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.YWXM
     *
     * @param ywxm the value for T_JZG.YWXM
     *
     * @mbggenerated
     */
    public void setYwxm(String ywxm) {
        this.ywxm = ywxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.SFZJYXQ
     *
     * @return the value of T_JZG.SFZJYXQ
     *
     * @mbggenerated
     */
    public String getSfzjyxq() {
        return sfzjyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.SFZJYXQ
     *
     * @param sfzjyxq the value for T_JZG.SFZJYXQ
     *
     * @mbggenerated
     */
    public void setSfzjyxq(String sfzjyxq) {
        this.sfzjyxq = sfzjyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.QXRQ
     *
     * @return the value of T_JZG.QXRQ
     *
     * @mbggenerated
     */
    public String getQxrq() {
        return qxrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.QXRQ
     *
     * @param qxrq the value for T_JZG.QXRQ
     *
     * @mbggenerated
     */
    public void setQxrq(String qxrq) {
        this.qxrq = qxrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.JG
     *
     * @return the value of T_JZG.JG
     *
     * @mbggenerated
     */
    public String getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.JG
     *
     * @param jg the value for T_JZG.JG
     *
     * @mbggenerated
     */
    public void setJg(String jg) {
        this.jg = jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.ZGXLM
     *
     * @return the value of T_JZG.ZGXLM
     *
     * @mbggenerated
     */
    public String getZgxlm() {
        return zgxlm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.ZGXLM
     *
     * @param zgxlm the value for T_JZG.ZGXLM
     *
     * @mbggenerated
     */
    public void setZgxlm(String zgxlm) {
        this.zgxlm = zgxlm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.BGDZ
     *
     * @return the value of T_JZG.BGDZ
     *
     * @mbggenerated
     */
    public String getBgdz() {
        return bgdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.BGDZ
     *
     * @param bgdz the value for T_JZG.BGDZ
     *
     * @mbggenerated
     */
    public void setBgdz(String bgdz) {
        this.bgdz = bgdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.BGDH
     *
     * @return the value of T_JZG.BGDH
     *
     * @mbggenerated
     */
    public String getBgdh() {
        return bgdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.BGDH
     *
     * @param bgdh the value for T_JZG.BGDH
     *
     * @mbggenerated
     */
    public void setBgdh(String bgdh) {
        this.bgdh = bgdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.GRDH
     *
     * @return the value of T_JZG.GRDH
     *
     * @mbggenerated
     */
    public String getGrdh() {
        return grdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.GRDH
     *
     * @param grdh the value for T_JZG.GRDH
     *
     * @mbggenerated
     */
    public void setGrdh(String grdh) {
        this.grdh = grdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.EMAIL
     *
     * @return the value of T_JZG.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.EMAIL
     *
     * @param email the value for T_JZG.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.SFZX
     *
     * @return the value of T_JZG.SFZX
     *
     * @mbggenerated
     */
    public Short getSfzx() {
        return sfzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.SFZX
     *
     * @param sfzx the value for T_JZG.SFZX
     *
     * @mbggenerated
     */
    public void setSfzx(Short sfzx) {
        this.sfzx = sfzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JZG.PX
     *
     * @return the value of T_JZG.PX
     *
     * @mbggenerated
     */
    public String getPx() {
        return px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JZG.PX
     *
     * @param px the value for T_JZG.PX
     *
     * @mbggenerated
     */
    public void setPx(String px) {
        this.px = px;
    }
}