package com.buptyouth.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class Undergraduate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.WID
     *
     * @mbggenerated
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XH
     *
     * @mbggenerated
     */
    private String schoolNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XM
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XMPY
     *
     * @mbggenerated
     */
    private String xmpy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.CYM
     *
     * @mbggenerated
     */
    private String cym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.YWM
     *
     * @mbggenerated
     */
    private String ywm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.MZDM
     *
     * @mbggenerated
     */
    private String mzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XBDM
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XXDM
     *
     * @mbggenerated
     */
    private String xxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.ZZMMDM
     *
     * @mbggenerated
     */
    private String zzmmdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SFZJLXM
     *
     * @mbggenerated
     */
    private String sfzjlxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SFZJH
     *
     * @mbggenerated
     */
    private String sfzjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.CSRQ
     *
     * @mbggenerated
     */
    private String csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.CSDDM
     *
     * @mbggenerated
     */
    private String csddm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.JGDM
     *
     * @mbggenerated
     */
    private String jgdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.JKZKDM
     *
     * @mbggenerated
     */
    private String jkzkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.HYZKDM
     *
     * @mbggenerated
     */
    private String hyzkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.GATQDM
     *
     * @mbggenerated
     */
    private String gatqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.GJDQDM
     *
     * @mbggenerated
     */
    private String gjdqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.BYZX
     *
     * @mbggenerated
     */
    private String byzx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.ZYDZ
     *
     * @mbggenerated
     */
    private String zydz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.CLRQ
     *
     * @mbggenerated
     */
    private Date clrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.CZLX
     *
     * @mbggenerated
     */
    private String czlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.CZZ
     *
     * @mbggenerated
     */
    private String czz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.BY1
     *
     * @mbggenerated
     */
    private String by1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.BY2
     *
     * @mbggenerated
     */
    private String by2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.JTCSDM
     *
     * @mbggenerated
     */
    private String jtcsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.LYZBDM
     *
     * @mbggenerated
     */
    private String lyzbdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SYDDM
     *
     * @mbggenerated
     */
    private String syddm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.HSSBKDM
     *
     * @mbggenerated
     */
    private String hssbkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XSLYDM
     *
     * @mbggenerated
     */
    private String xslydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.HKXZDM
     *
     * @mbggenerated
     */
    private String hkxzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.HKSZD
     *
     * @mbggenerated
     */
    private String hkszd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.YXDM
     *
     * @mbggenerated
     */
    private String collegeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.ZYDM
     *
     * @mbggenerated
     */
    private String zydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XKMLDM
     *
     * @mbggenerated
     */
    private String xkmldm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.ZYFXDM
     *
     * @mbggenerated
     */
    private String zyfxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.JDFSDM
     *
     * @mbggenerated
     */
    private String jdfsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.PYFSDM
     *
     * @mbggenerated
     */
    private String pyfsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.WTPYDW
     *
     * @mbggenerated
     */
    private String wtpydw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XSLBDM
     *
     * @mbggenerated
     */
    private String xslbdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.DYWYYZDM
     *
     * @mbggenerated
     */
    private String dywyyzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.DYWYSPDM
     *
     * @mbggenerated
     */
    private String dywyspdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.DEWYYZDM
     *
     * @mbggenerated
     */
    private String dewyyzdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.DEWYSPDM
     *
     * @mbggenerated
     */
    private String dewyspdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.DSZGH
     *
     * @mbggenerated
     */
    private String dszgh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.RXNJ
     *
     * @mbggenerated
     */
    private String rxnj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XZNJ
     *
     * @mbggenerated
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.RXNY
     *
     * @mbggenerated
     */
    private String rxny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XZZYDM
     *
     * @mbggenerated
     */
    private String xzzydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.BH
     *
     * @mbggenerated
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XZ
     *
     * @mbggenerated
     */
    private BigDecimal xz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.JDXWDM
     *
     * @mbggenerated
     */
    private String jdxwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.JDXLDM
     *
     * @mbggenerated
     */
    private String jdxldm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.YJBYNF
     *
     * @mbggenerated
     */
    private String yjbynf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.YJBYJD
     *
     * @mbggenerated
     */
    private String yjbyjd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.TZ
     *
     * @mbggenerated
     */
    private BigDecimal tz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SJBYSJ
     *
     * @mbggenerated
     */
    private String sjbysj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SG
     *
     * @mbggenerated
     */
    private BigDecimal sg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.ZHPC
     *
     * @mbggenerated
     */
    private String zhpc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.ZCQK
     *
     * @mbggenerated
     */
    private String registerInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SFZX
     *
     * @mbggenerated
     */
    private String sfzx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XJZT
     *
     * @mbggenerated
     */
    private String xjzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SJLY
     *
     * @mbggenerated
     */
    private String sjly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.DQZTDM
     *
     * @mbggenerated
     */
    private String dqztdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SJBBH
     *
     * @mbggenerated
     */
    private String sjbbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.HDXLFSDM
     *
     * @mbggenerated
     */
    private String hdxlfsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SFXFZ
     *
     * @mbggenerated
     */
    private String sfxfz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.LDFSDM
     *
     * @mbggenerated
     */
    private String ldfsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.PYCCDM
     *
     * @mbggenerated
     */
    private String pyccdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.GATQWDM
     *
     * @mbggenerated
     */
    private String gatqwdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.XYZJDM
     *
     * @mbggenerated
     */
    private String xyzjdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SFZJYXQ
     *
     * @mbggenerated
     */
    private String sfzjyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SFDSZN
     *
     * @mbggenerated
     */
    private String sfdszn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.YXH
     *
     * @mbggenerated
     */
    private String yxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.LYDQDM
     *
     * @mbggenerated
     */
    private String lydqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.JG
     *
     * @mbggenerated
     */
    private String jg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.GRDH1
     *
     * @mbggenerated
     */
    private String grdh1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.GRDH2
     *
     * @mbggenerated
     */
    private String grdh2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.EMAIL1
     *
     * @mbggenerated
     */
    private String email1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.EMAIL2
     *
     * @mbggenerated
     */
    private String email2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.TSXSLXM
     *
     * @mbggenerated
     */
    private String tsxslxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SFBY
     *
     * @mbggenerated
     */
    private String sfby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SS
     *
     * @mbggenerated
     */
    private String ss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.SSDH
     *
     * @mbggenerated
     */
    private String ssdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BZKS.ZP
     *
     * @mbggenerated
     */
    private byte[] zp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.WID
     *
     * @return the value of T_BZKS.WID
     *
     * @mbggenerated
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.WID
     *
     * @param wid the value for T_BZKS.WID
     *
     * @mbggenerated
     */
    public void setWid(String wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XH
     *
     * @return the value of T_BZKS.XH
     *
     * @mbggenerated
     */
    public String getSchoolNumber() {
        return schoolNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XH
     *
     * @param schoolNumber the value for T_BZKS.XH
     *
     * @mbggenerated
     */
    public void setSchoolNumber(String schoolNumber) {
        this.schoolNumber = schoolNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XM
     *
     * @return the value of T_BZKS.XM
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XM
     *
     * @param userName the value for T_BZKS.XM
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XMPY
     *
     * @return the value of T_BZKS.XMPY
     *
     * @mbggenerated
     */
    public String getXmpy() {
        return xmpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XMPY
     *
     * @param xmpy the value for T_BZKS.XMPY
     *
     * @mbggenerated
     */
    public void setXmpy(String xmpy) {
        this.xmpy = xmpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.CYM
     *
     * @return the value of T_BZKS.CYM
     *
     * @mbggenerated
     */
    public String getCym() {
        return cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.CYM
     *
     * @param cym the value for T_BZKS.CYM
     *
     * @mbggenerated
     */
    public void setCym(String cym) {
        this.cym = cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.YWM
     *
     * @return the value of T_BZKS.YWM
     *
     * @mbggenerated
     */
    public String getYwm() {
        return ywm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.YWM
     *
     * @param ywm the value for T_BZKS.YWM
     *
     * @mbggenerated
     */
    public void setYwm(String ywm) {
        this.ywm = ywm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.MZDM
     *
     * @return the value of T_BZKS.MZDM
     *
     * @mbggenerated
     */
    public String getMzdm() {
        return mzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.MZDM
     *
     * @param mzdm the value for T_BZKS.MZDM
     *
     * @mbggenerated
     */
    public void setMzdm(String mzdm) {
        this.mzdm = mzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XBDM
     *
     * @return the value of T_BZKS.XBDM
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XBDM
     *
     * @param gender the value for T_BZKS.XBDM
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XXDM
     *
     * @return the value of T_BZKS.XXDM
     *
     * @mbggenerated
     */
    public String getXxdm() {
        return xxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XXDM
     *
     * @param xxdm the value for T_BZKS.XXDM
     *
     * @mbggenerated
     */
    public void setXxdm(String xxdm) {
        this.xxdm = xxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.ZZMMDM
     *
     * @return the value of T_BZKS.ZZMMDM
     *
     * @mbggenerated
     */
    public String getZzmmdm() {
        return zzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.ZZMMDM
     *
     * @param zzmmdm the value for T_BZKS.ZZMMDM
     *
     * @mbggenerated
     */
    public void setZzmmdm(String zzmmdm) {
        this.zzmmdm = zzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SFZJLXM
     *
     * @return the value of T_BZKS.SFZJLXM
     *
     * @mbggenerated
     */
    public String getSfzjlxm() {
        return sfzjlxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SFZJLXM
     *
     * @param sfzjlxm the value for T_BZKS.SFZJLXM
     *
     * @mbggenerated
     */
    public void setSfzjlxm(String sfzjlxm) {
        this.sfzjlxm = sfzjlxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SFZJH
     *
     * @return the value of T_BZKS.SFZJH
     *
     * @mbggenerated
     */
    public String getSfzjh() {
        return sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SFZJH
     *
     * @param sfzjh the value for T_BZKS.SFZJH
     *
     * @mbggenerated
     */
    public void setSfzjh(String sfzjh) {
        this.sfzjh = sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.CSRQ
     *
     * @return the value of T_BZKS.CSRQ
     *
     * @mbggenerated
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.CSRQ
     *
     * @param csrq the value for T_BZKS.CSRQ
     *
     * @mbggenerated
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.CSDDM
     *
     * @return the value of T_BZKS.CSDDM
     *
     * @mbggenerated
     */
    public String getCsddm() {
        return csddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.CSDDM
     *
     * @param csddm the value for T_BZKS.CSDDM
     *
     * @mbggenerated
     */
    public void setCsddm(String csddm) {
        this.csddm = csddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.JGDM
     *
     * @return the value of T_BZKS.JGDM
     *
     * @mbggenerated
     */
    public String getJgdm() {
        return jgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.JGDM
     *
     * @param jgdm the value for T_BZKS.JGDM
     *
     * @mbggenerated
     */
    public void setJgdm(String jgdm) {
        this.jgdm = jgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.JKZKDM
     *
     * @return the value of T_BZKS.JKZKDM
     *
     * @mbggenerated
     */
    public String getJkzkdm() {
        return jkzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.JKZKDM
     *
     * @param jkzkdm the value for T_BZKS.JKZKDM
     *
     * @mbggenerated
     */
    public void setJkzkdm(String jkzkdm) {
        this.jkzkdm = jkzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.HYZKDM
     *
     * @return the value of T_BZKS.HYZKDM
     *
     * @mbggenerated
     */
    public String getHyzkdm() {
        return hyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.HYZKDM
     *
     * @param hyzkdm the value for T_BZKS.HYZKDM
     *
     * @mbggenerated
     */
    public void setHyzkdm(String hyzkdm) {
        this.hyzkdm = hyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.GATQDM
     *
     * @return the value of T_BZKS.GATQDM
     *
     * @mbggenerated
     */
    public String getGatqdm() {
        return gatqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.GATQDM
     *
     * @param gatqdm the value for T_BZKS.GATQDM
     *
     * @mbggenerated
     */
    public void setGatqdm(String gatqdm) {
        this.gatqdm = gatqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.GJDQDM
     *
     * @return the value of T_BZKS.GJDQDM
     *
     * @mbggenerated
     */
    public String getGjdqdm() {
        return gjdqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.GJDQDM
     *
     * @param gjdqdm the value for T_BZKS.GJDQDM
     *
     * @mbggenerated
     */
    public void setGjdqdm(String gjdqdm) {
        this.gjdqdm = gjdqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.BYZX
     *
     * @return the value of T_BZKS.BYZX
     *
     * @mbggenerated
     */
    public String getByzx() {
        return byzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.BYZX
     *
     * @param byzx the value for T_BZKS.BYZX
     *
     * @mbggenerated
     */
    public void setByzx(String byzx) {
        this.byzx = byzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.ZYDZ
     *
     * @return the value of T_BZKS.ZYDZ
     *
     * @mbggenerated
     */
    public String getZydz() {
        return zydz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.ZYDZ
     *
     * @param zydz the value for T_BZKS.ZYDZ
     *
     * @mbggenerated
     */
    public void setZydz(String zydz) {
        this.zydz = zydz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.CLRQ
     *
     * @return the value of T_BZKS.CLRQ
     *
     * @mbggenerated
     */
    public Date getClrq() {
        return clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.CLRQ
     *
     * @param clrq the value for T_BZKS.CLRQ
     *
     * @mbggenerated
     */
    public void setClrq(Date clrq) {
        this.clrq = clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.CZLX
     *
     * @return the value of T_BZKS.CZLX
     *
     * @mbggenerated
     */
    public String getCzlx() {
        return czlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.CZLX
     *
     * @param czlx the value for T_BZKS.CZLX
     *
     * @mbggenerated
     */
    public void setCzlx(String czlx) {
        this.czlx = czlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.CZZ
     *
     * @return the value of T_BZKS.CZZ
     *
     * @mbggenerated
     */
    public String getCzz() {
        return czz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.CZZ
     *
     * @param czz the value for T_BZKS.CZZ
     *
     * @mbggenerated
     */
    public void setCzz(String czz) {
        this.czz = czz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.BY1
     *
     * @return the value of T_BZKS.BY1
     *
     * @mbggenerated
     */
    public String getBy1() {
        return by1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.BY1
     *
     * @param by1 the value for T_BZKS.BY1
     *
     * @mbggenerated
     */
    public void setBy1(String by1) {
        this.by1 = by1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.BY2
     *
     * @return the value of T_BZKS.BY2
     *
     * @mbggenerated
     */
    public String getBy2() {
        return by2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.BY2
     *
     * @param by2 the value for T_BZKS.BY2
     *
     * @mbggenerated
     */
    public void setBy2(String by2) {
        this.by2 = by2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.JTCSDM
     *
     * @return the value of T_BZKS.JTCSDM
     *
     * @mbggenerated
     */
    public String getJtcsdm() {
        return jtcsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.JTCSDM
     *
     * @param jtcsdm the value for T_BZKS.JTCSDM
     *
     * @mbggenerated
     */
    public void setJtcsdm(String jtcsdm) {
        this.jtcsdm = jtcsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.LYZBDM
     *
     * @return the value of T_BZKS.LYZBDM
     *
     * @mbggenerated
     */
    public String getLyzbdm() {
        return lyzbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.LYZBDM
     *
     * @param lyzbdm the value for T_BZKS.LYZBDM
     *
     * @mbggenerated
     */
    public void setLyzbdm(String lyzbdm) {
        this.lyzbdm = lyzbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SYDDM
     *
     * @return the value of T_BZKS.SYDDM
     *
     * @mbggenerated
     */
    public String getSyddm() {
        return syddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SYDDM
     *
     * @param syddm the value for T_BZKS.SYDDM
     *
     * @mbggenerated
     */
    public void setSyddm(String syddm) {
        this.syddm = syddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.HSSBKDM
     *
     * @return the value of T_BZKS.HSSBKDM
     *
     * @mbggenerated
     */
    public String getHssbkdm() {
        return hssbkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.HSSBKDM
     *
     * @param hssbkdm the value for T_BZKS.HSSBKDM
     *
     * @mbggenerated
     */
    public void setHssbkdm(String hssbkdm) {
        this.hssbkdm = hssbkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XSLYDM
     *
     * @return the value of T_BZKS.XSLYDM
     *
     * @mbggenerated
     */
    public String getXslydm() {
        return xslydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XSLYDM
     *
     * @param xslydm the value for T_BZKS.XSLYDM
     *
     * @mbggenerated
     */
    public void setXslydm(String xslydm) {
        this.xslydm = xslydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.HKXZDM
     *
     * @return the value of T_BZKS.HKXZDM
     *
     * @mbggenerated
     */
    public String getHkxzdm() {
        return hkxzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.HKXZDM
     *
     * @param hkxzdm the value for T_BZKS.HKXZDM
     *
     * @mbggenerated
     */
    public void setHkxzdm(String hkxzdm) {
        this.hkxzdm = hkxzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.HKSZD
     *
     * @return the value of T_BZKS.HKSZD
     *
     * @mbggenerated
     */
    public String getHkszd() {
        return hkszd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.HKSZD
     *
     * @param hkszd the value for T_BZKS.HKSZD
     *
     * @mbggenerated
     */
    public void setHkszd(String hkszd) {
        this.hkszd = hkszd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.YXDM
     *
     * @return the value of T_BZKS.YXDM
     *
     * @mbggenerated
     */
    public String getCollegeCode() {
        return collegeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.YXDM
     *
     * @param collegeCode the value for T_BZKS.YXDM
     *
     * @mbggenerated
     */
    public void setCollegeCode(String collegeCode) {
        this.collegeCode = collegeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.ZYDM
     *
     * @return the value of T_BZKS.ZYDM
     *
     * @mbggenerated
     */
    public String getZydm() {
        return zydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.ZYDM
     *
     * @param zydm the value for T_BZKS.ZYDM
     *
     * @mbggenerated
     */
    public void setZydm(String zydm) {
        this.zydm = zydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XKMLDM
     *
     * @return the value of T_BZKS.XKMLDM
     *
     * @mbggenerated
     */
    public String getXkmldm() {
        return xkmldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XKMLDM
     *
     * @param xkmldm the value for T_BZKS.XKMLDM
     *
     * @mbggenerated
     */
    public void setXkmldm(String xkmldm) {
        this.xkmldm = xkmldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.ZYFXDM
     *
     * @return the value of T_BZKS.ZYFXDM
     *
     * @mbggenerated
     */
    public String getZyfxdm() {
        return zyfxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.ZYFXDM
     *
     * @param zyfxdm the value for T_BZKS.ZYFXDM
     *
     * @mbggenerated
     */
    public void setZyfxdm(String zyfxdm) {
        this.zyfxdm = zyfxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.JDFSDM
     *
     * @return the value of T_BZKS.JDFSDM
     *
     * @mbggenerated
     */
    public String getJdfsdm() {
        return jdfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.JDFSDM
     *
     * @param jdfsdm the value for T_BZKS.JDFSDM
     *
     * @mbggenerated
     */
    public void setJdfsdm(String jdfsdm) {
        this.jdfsdm = jdfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.PYFSDM
     *
     * @return the value of T_BZKS.PYFSDM
     *
     * @mbggenerated
     */
    public String getPyfsdm() {
        return pyfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.PYFSDM
     *
     * @param pyfsdm the value for T_BZKS.PYFSDM
     *
     * @mbggenerated
     */
    public void setPyfsdm(String pyfsdm) {
        this.pyfsdm = pyfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.WTPYDW
     *
     * @return the value of T_BZKS.WTPYDW
     *
     * @mbggenerated
     */
    public String getWtpydw() {
        return wtpydw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.WTPYDW
     *
     * @param wtpydw the value for T_BZKS.WTPYDW
     *
     * @mbggenerated
     */
    public void setWtpydw(String wtpydw) {
        this.wtpydw = wtpydw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XSLBDM
     *
     * @return the value of T_BZKS.XSLBDM
     *
     * @mbggenerated
     */
    public String getXslbdm() {
        return xslbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XSLBDM
     *
     * @param xslbdm the value for T_BZKS.XSLBDM
     *
     * @mbggenerated
     */
    public void setXslbdm(String xslbdm) {
        this.xslbdm = xslbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.DYWYYZDM
     *
     * @return the value of T_BZKS.DYWYYZDM
     *
     * @mbggenerated
     */
    public String getDywyyzdm() {
        return dywyyzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.DYWYYZDM
     *
     * @param dywyyzdm the value for T_BZKS.DYWYYZDM
     *
     * @mbggenerated
     */
    public void setDywyyzdm(String dywyyzdm) {
        this.dywyyzdm = dywyyzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.DYWYSPDM
     *
     * @return the value of T_BZKS.DYWYSPDM
     *
     * @mbggenerated
     */
    public String getDywyspdm() {
        return dywyspdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.DYWYSPDM
     *
     * @param dywyspdm the value for T_BZKS.DYWYSPDM
     *
     * @mbggenerated
     */
    public void setDywyspdm(String dywyspdm) {
        this.dywyspdm = dywyspdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.DEWYYZDM
     *
     * @return the value of T_BZKS.DEWYYZDM
     *
     * @mbggenerated
     */
    public String getDewyyzdm() {
        return dewyyzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.DEWYYZDM
     *
     * @param dewyyzdm the value for T_BZKS.DEWYYZDM
     *
     * @mbggenerated
     */
    public void setDewyyzdm(String dewyyzdm) {
        this.dewyyzdm = dewyyzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.DEWYSPDM
     *
     * @return the value of T_BZKS.DEWYSPDM
     *
     * @mbggenerated
     */
    public String getDewyspdm() {
        return dewyspdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.DEWYSPDM
     *
     * @param dewyspdm the value for T_BZKS.DEWYSPDM
     *
     * @mbggenerated
     */
    public void setDewyspdm(String dewyspdm) {
        this.dewyspdm = dewyspdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.DSZGH
     *
     * @return the value of T_BZKS.DSZGH
     *
     * @mbggenerated
     */
    public String getDszgh() {
        return dszgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.DSZGH
     *
     * @param dszgh the value for T_BZKS.DSZGH
     *
     * @mbggenerated
     */
    public void setDszgh(String dszgh) {
        this.dszgh = dszgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.RXNJ
     *
     * @return the value of T_BZKS.RXNJ
     *
     * @mbggenerated
     */
    public String getRxnj() {
        return rxnj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.RXNJ
     *
     * @param rxnj the value for T_BZKS.RXNJ
     *
     * @mbggenerated
     */
    public void setRxnj(String rxnj) {
        this.rxnj = rxnj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XZNJ
     *
     * @return the value of T_BZKS.XZNJ
     *
     * @mbggenerated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XZNJ
     *
     * @param grade the value for T_BZKS.XZNJ
     *
     * @mbggenerated
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.RXNY
     *
     * @return the value of T_BZKS.RXNY
     *
     * @mbggenerated
     */
    public String getRxny() {
        return rxny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.RXNY
     *
     * @param rxny the value for T_BZKS.RXNY
     *
     * @mbggenerated
     */
    public void setRxny(String rxny) {
        this.rxny = rxny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XZZYDM
     *
     * @return the value of T_BZKS.XZZYDM
     *
     * @mbggenerated
     */
    public String getXzzydm() {
        return xzzydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XZZYDM
     *
     * @param xzzydm the value for T_BZKS.XZZYDM
     *
     * @mbggenerated
     */
    public void setXzzydm(String xzzydm) {
        this.xzzydm = xzzydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.BH
     *
     * @return the value of T_BZKS.BH
     *
     * @mbggenerated
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.BH
     *
     * @param bh the value for T_BZKS.BH
     *
     * @mbggenerated
     */
    public void setBh(String bh) {
        this.bh = bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XZ
     *
     * @return the value of T_BZKS.XZ
     *
     * @mbggenerated
     */
    public BigDecimal getXz() {
        return xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XZ
     *
     * @param xz the value for T_BZKS.XZ
     *
     * @mbggenerated
     */
    public void setXz(BigDecimal xz) {
        this.xz = xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.JDXWDM
     *
     * @return the value of T_BZKS.JDXWDM
     *
     * @mbggenerated
     */
    public String getJdxwdm() {
        return jdxwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.JDXWDM
     *
     * @param jdxwdm the value for T_BZKS.JDXWDM
     *
     * @mbggenerated
     */
    public void setJdxwdm(String jdxwdm) {
        this.jdxwdm = jdxwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.JDXLDM
     *
     * @return the value of T_BZKS.JDXLDM
     *
     * @mbggenerated
     */
    public String getJdxldm() {
        return jdxldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.JDXLDM
     *
     * @param jdxldm the value for T_BZKS.JDXLDM
     *
     * @mbggenerated
     */
    public void setJdxldm(String jdxldm) {
        this.jdxldm = jdxldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.YJBYNF
     *
     * @return the value of T_BZKS.YJBYNF
     *
     * @mbggenerated
     */
    public String getYjbynf() {
        return yjbynf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.YJBYNF
     *
     * @param yjbynf the value for T_BZKS.YJBYNF
     *
     * @mbggenerated
     */
    public void setYjbynf(String yjbynf) {
        this.yjbynf = yjbynf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.YJBYJD
     *
     * @return the value of T_BZKS.YJBYJD
     *
     * @mbggenerated
     */
    public String getYjbyjd() {
        return yjbyjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.YJBYJD
     *
     * @param yjbyjd the value for T_BZKS.YJBYJD
     *
     * @mbggenerated
     */
    public void setYjbyjd(String yjbyjd) {
        this.yjbyjd = yjbyjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.TZ
     *
     * @return the value of T_BZKS.TZ
     *
     * @mbggenerated
     */
    public BigDecimal getTz() {
        return tz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.TZ
     *
     * @param tz the value for T_BZKS.TZ
     *
     * @mbggenerated
     */
    public void setTz(BigDecimal tz) {
        this.tz = tz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SJBYSJ
     *
     * @return the value of T_BZKS.SJBYSJ
     *
     * @mbggenerated
     */
    public String getSjbysj() {
        return sjbysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SJBYSJ
     *
     * @param sjbysj the value for T_BZKS.SJBYSJ
     *
     * @mbggenerated
     */
    public void setSjbysj(String sjbysj) {
        this.sjbysj = sjbysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SG
     *
     * @return the value of T_BZKS.SG
     *
     * @mbggenerated
     */
    public BigDecimal getSg() {
        return sg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SG
     *
     * @param sg the value for T_BZKS.SG
     *
     * @mbggenerated
     */
    public void setSg(BigDecimal sg) {
        this.sg = sg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.ZHPC
     *
     * @return the value of T_BZKS.ZHPC
     *
     * @mbggenerated
     */
    public String getZhpc() {
        return zhpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.ZHPC
     *
     * @param zhpc the value for T_BZKS.ZHPC
     *
     * @mbggenerated
     */
    public void setZhpc(String zhpc) {
        this.zhpc = zhpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.ZCQK
     *
     * @return the value of T_BZKS.ZCQK
     *
     * @mbggenerated
     */
    public String getRegisterInfo() {
        return registerInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.ZCQK
     *
     * @param registerInfo the value for T_BZKS.ZCQK
     *
     * @mbggenerated
     */
    public void setRegisterInfo(String registerInfo) {
        this.registerInfo = registerInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SFZX
     *
     * @return the value of T_BZKS.SFZX
     *
     * @mbggenerated
     */
    public String getSfzx() {
        return sfzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SFZX
     *
     * @param sfzx the value for T_BZKS.SFZX
     *
     * @mbggenerated
     */
    public void setSfzx(String sfzx) {
        this.sfzx = sfzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XJZT
     *
     * @return the value of T_BZKS.XJZT
     *
     * @mbggenerated
     */
    public String getXjzt() {
        return xjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XJZT
     *
     * @param xjzt the value for T_BZKS.XJZT
     *
     * @mbggenerated
     */
    public void setXjzt(String xjzt) {
        this.xjzt = xjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SJLY
     *
     * @return the value of T_BZKS.SJLY
     *
     * @mbggenerated
     */
    public String getSjly() {
        return sjly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SJLY
     *
     * @param sjly the value for T_BZKS.SJLY
     *
     * @mbggenerated
     */
    public void setSjly(String sjly) {
        this.sjly = sjly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.DQZTDM
     *
     * @return the value of T_BZKS.DQZTDM
     *
     * @mbggenerated
     */
    public String getDqztdm() {
        return dqztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.DQZTDM
     *
     * @param dqztdm the value for T_BZKS.DQZTDM
     *
     * @mbggenerated
     */
    public void setDqztdm(String dqztdm) {
        this.dqztdm = dqztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SJBBH
     *
     * @return the value of T_BZKS.SJBBH
     *
     * @mbggenerated
     */
    public String getSjbbh() {
        return sjbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SJBBH
     *
     * @param sjbbh the value for T_BZKS.SJBBH
     *
     * @mbggenerated
     */
    public void setSjbbh(String sjbbh) {
        this.sjbbh = sjbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.HDXLFSDM
     *
     * @return the value of T_BZKS.HDXLFSDM
     *
     * @mbggenerated
     */
    public String getHdxlfsdm() {
        return hdxlfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.HDXLFSDM
     *
     * @param hdxlfsdm the value for T_BZKS.HDXLFSDM
     *
     * @mbggenerated
     */
    public void setHdxlfsdm(String hdxlfsdm) {
        this.hdxlfsdm = hdxlfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SFXFZ
     *
     * @return the value of T_BZKS.SFXFZ
     *
     * @mbggenerated
     */
    public String getSfxfz() {
        return sfxfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SFXFZ
     *
     * @param sfxfz the value for T_BZKS.SFXFZ
     *
     * @mbggenerated
     */
    public void setSfxfz(String sfxfz) {
        this.sfxfz = sfxfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.LDFSDM
     *
     * @return the value of T_BZKS.LDFSDM
     *
     * @mbggenerated
     */
    public String getLdfsdm() {
        return ldfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.LDFSDM
     *
     * @param ldfsdm the value for T_BZKS.LDFSDM
     *
     * @mbggenerated
     */
    public void setLdfsdm(String ldfsdm) {
        this.ldfsdm = ldfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.PYCCDM
     *
     * @return the value of T_BZKS.PYCCDM
     *
     * @mbggenerated
     */
    public String getPyccdm() {
        return pyccdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.PYCCDM
     *
     * @param pyccdm the value for T_BZKS.PYCCDM
     *
     * @mbggenerated
     */
    public void setPyccdm(String pyccdm) {
        this.pyccdm = pyccdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.GATQWDM
     *
     * @return the value of T_BZKS.GATQWDM
     *
     * @mbggenerated
     */
    public String getGatqwdm() {
        return gatqwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.GATQWDM
     *
     * @param gatqwdm the value for T_BZKS.GATQWDM
     *
     * @mbggenerated
     */
    public void setGatqwdm(String gatqwdm) {
        this.gatqwdm = gatqwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.XYZJDM
     *
     * @return the value of T_BZKS.XYZJDM
     *
     * @mbggenerated
     */
    public String getXyzjdm() {
        return xyzjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.XYZJDM
     *
     * @param xyzjdm the value for T_BZKS.XYZJDM
     *
     * @mbggenerated
     */
    public void setXyzjdm(String xyzjdm) {
        this.xyzjdm = xyzjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SFZJYXQ
     *
     * @return the value of T_BZKS.SFZJYXQ
     *
     * @mbggenerated
     */
    public String getSfzjyxq() {
        return sfzjyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SFZJYXQ
     *
     * @param sfzjyxq the value for T_BZKS.SFZJYXQ
     *
     * @mbggenerated
     */
    public void setSfzjyxq(String sfzjyxq) {
        this.sfzjyxq = sfzjyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SFDSZN
     *
     * @return the value of T_BZKS.SFDSZN
     *
     * @mbggenerated
     */
    public String getSfdszn() {
        return sfdszn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SFDSZN
     *
     * @param sfdszn the value for T_BZKS.SFDSZN
     *
     * @mbggenerated
     */
    public void setSfdszn(String sfdszn) {
        this.sfdszn = sfdszn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.YXH
     *
     * @return the value of T_BZKS.YXH
     *
     * @mbggenerated
     */
    public String getYxh() {
        return yxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.YXH
     *
     * @param yxh the value for T_BZKS.YXH
     *
     * @mbggenerated
     */
    public void setYxh(String yxh) {
        this.yxh = yxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.LYDQDM
     *
     * @return the value of T_BZKS.LYDQDM
     *
     * @mbggenerated
     */
    public String getLydqdm() {
        return lydqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.LYDQDM
     *
     * @param lydqdm the value for T_BZKS.LYDQDM
     *
     * @mbggenerated
     */
    public void setLydqdm(String lydqdm) {
        this.lydqdm = lydqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.JG
     *
     * @return the value of T_BZKS.JG
     *
     * @mbggenerated
     */
    public String getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.JG
     *
     * @param jg the value for T_BZKS.JG
     *
     * @mbggenerated
     */
    public void setJg(String jg) {
        this.jg = jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.GRDH1
     *
     * @return the value of T_BZKS.GRDH1
     *
     * @mbggenerated
     */
    public String getGrdh1() {
        return grdh1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.GRDH1
     *
     * @param grdh1 the value for T_BZKS.GRDH1
     *
     * @mbggenerated
     */
    public void setGrdh1(String grdh1) {
        this.grdh1 = grdh1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.GRDH2
     *
     * @return the value of T_BZKS.GRDH2
     *
     * @mbggenerated
     */
    public String getGrdh2() {
        return grdh2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.GRDH2
     *
     * @param grdh2 the value for T_BZKS.GRDH2
     *
     * @mbggenerated
     */
    public void setGrdh2(String grdh2) {
        this.grdh2 = grdh2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.EMAIL1
     *
     * @return the value of T_BZKS.EMAIL1
     *
     * @mbggenerated
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.EMAIL1
     *
     * @param email1 the value for T_BZKS.EMAIL1
     *
     * @mbggenerated
     */
    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.EMAIL2
     *
     * @return the value of T_BZKS.EMAIL2
     *
     * @mbggenerated
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.EMAIL2
     *
     * @param email2 the value for T_BZKS.EMAIL2
     *
     * @mbggenerated
     */
    public void setEmail2(String email2) {
        this.email2 = email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.TSXSLXM
     *
     * @return the value of T_BZKS.TSXSLXM
     *
     * @mbggenerated
     */
    public String getTsxslxm() {
        return tsxslxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.TSXSLXM
     *
     * @param tsxslxm the value for T_BZKS.TSXSLXM
     *
     * @mbggenerated
     */
    public void setTsxslxm(String tsxslxm) {
        this.tsxslxm = tsxslxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SFBY
     *
     * @return the value of T_BZKS.SFBY
     *
     * @mbggenerated
     */
    public String getSfby() {
        return sfby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SFBY
     *
     * @param sfby the value for T_BZKS.SFBY
     *
     * @mbggenerated
     */
    public void setSfby(String sfby) {
        this.sfby = sfby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SS
     *
     * @return the value of T_BZKS.SS
     *
     * @mbggenerated
     */
    public String getSs() {
        return ss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SS
     *
     * @param ss the value for T_BZKS.SS
     *
     * @mbggenerated
     */
    public void setSs(String ss) {
        this.ss = ss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.SSDH
     *
     * @return the value of T_BZKS.SSDH
     *
     * @mbggenerated
     */
    public String getSsdh() {
        return ssdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.SSDH
     *
     * @param ssdh the value for T_BZKS.SSDH
     *
     * @mbggenerated
     */
    public void setSsdh(String ssdh) {
        this.ssdh = ssdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BZKS.ZP
     *
     * @return the value of T_BZKS.ZP
     *
     * @mbggenerated
     */
    public byte[] getZp() {
        return zp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BZKS.ZP
     *
     * @param zp the value for T_BZKS.ZP
     *
     * @mbggenerated
     */
    public void setZp(byte[] zp) {
        this.zp = zp;
    }
}