package com.buptyouth.mybatis.model;

public class UserAccess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userAccess.role
     *
     * @mbggenerated
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userAccess.access
     *
     * @mbggenerated
     */
    private String access;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userAccess.role
     *
     * @return the value of userAccess.role
     *
     * @mbggenerated
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userAccess.role
     *
     * @param role the value for userAccess.role
     *
     * @mbggenerated
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userAccess.access
     *
     * @return the value of userAccess.access
     *
     * @mbggenerated
     */
    public String getAccess() {
        return access;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userAccess.access
     *
     * @param access the value for userAccess.access
     *
     * @mbggenerated
     */
    public void setAccess(String access) {
        this.access = access;
    }
}