package com.buptyouth.mybatis.model;

public class Userwechat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwechat.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwechat.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwechat.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwechat.college
     *
     * @mbggenerated
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwechat.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwechat.user_id
     *
     * @return the value of userwechat.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwechat.user_id
     *
     * @param userId the value for userwechat.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwechat.open_id
     *
     * @return the value of userwechat.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwechat.open_id
     *
     * @param openId the value for userwechat.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwechat.code
     *
     * @return the value of userwechat.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwechat.code
     *
     * @param code the value for userwechat.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwechat.college
     *
     * @return the value of userwechat.college
     *
     * @mbggenerated
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwechat.college
     *
     * @param college the value for userwechat.college
     *
     * @mbggenerated
     */
    public void setCollege(String college) {
        this.college = college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwechat.department
     *
     * @return the value of userwechat.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwechat.department
     *
     * @param department the value for userwechat.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department;
    }
}